### ISSUE TITLE
Use correct hathi data API paths

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#106]
## notes for testing
- On a non-retina screen it should be very difficult (maybe impossible) to get image throttling from Hathi (we're now using the thumbnail API for lower-res page images)
- On a retina screen, it should be harder to trigger now that we're lazy-loading and not loading as many images at once, but still possible. When you do trigger image throttling, you should see a lower-quality page preview image instead of the hathi 'image unavailable' error image. (You may or may not briefly see the error image before it switches)

## dev notes
update 2/12/19: hathi has responded and given us some pointers on working with the thumbnail API, which should reduce throttling. we can change the image requests in the template to use this API.

**Comment by rlskoeser** [comment]
Documentation on the Hathi Data API probably relevant here: https://www.hathitrust.org/documents/hathitrust-data-api.pdf

**Comment by rlskoeser** [comment]
Happened on the error, it looks like the width set in the styles is making this display better than it was previously. We should probably still look into the data api and find out more about throttling and quotas, though.

<img width="1168" alt="screen shot 2018-11-02 at 1 45 34 pm" src="https://user-images.githubusercontent.com/691231/47931596-a7252680-dea5-11e8-8cef-2fb910142340.png">

**Comment by thatbudakguy** [comment]
Contacted hathi 11/27 to ask about this.

**Comment by thatbudakguy** [comment]
Based on hathi's response, we can probably switch to using the thumbnail API, which serves slightly smaller images but could lessen the throttling.

**Comment by rlskoeser** [comment]
I did some investigation, and it looks like the thumbnail goes up to 250 width. We can use that for the 1x but it's a significant downgrade to display that for retina screens. What I think we can do is use the thumbnail api for 1x and image api for 2x.  Implementing lazy loading #176 will help some, but I think that if we also add a [check for image load](https://stackoverflow.com/questions/9815762/detect-when-an-image-fails-to-load-in-javascript) failures on the 2x version, if we remove that srcset attribute the browser should display the 1x version instead - so users will just be downgraded to a lower res version of the image rather than the 'image unavailable' image.

**Comment by mnaydan** [comment]
Testing is dependent on fixing #176 first because I can't see the thumbnails at all right now.

**Comment by mnaydan** [comment]
I'm not quite sure how to test this, but since I've been working with the site for a few days doing various searches I haven't been throttled, so I'm going to sign off on it.
