### ISSUE TITLE
 Style updates: homepage

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#107]
## testing notes
**designs**
[desktop](https://zpl.io/amyZ6mr) / [tablet](https://zpl.io/boZXxwk) / [mobile](https://zpl.io/brlZr9X)

**Comment by mnaydan** [comment]
My comments below are mostly for desktop but the bigger design stuff obviously applies to iPad/iPhone too. iPad and iPhone generally look good. My comments about collections tile size, lining up the collections blurb with the tiles on the left margin for iPhone, and touch interaction apply here too (see my comment on #115). The parallax effect on iPad and iPhone is so trippy I love it! It responds to the way you move the iPad/phone. 
 
- **Logo size:** The logo size matches with Zeplin but I think it's way too big. On my Mac I can barely see that there's text below to suggest that I should scroll down. Can we shrink it a bit so that more of the text is visible? 
- **Background:** This is probably not a priority for launching, or it may be something to talk to Gissoo and @rlskoeser about, but I think the prosody symbols in the background are barely visible. It might work better if they were a shade darker than the background color and increased in transparency toward the logo. 
- **About the collections section:** The blurb ("The Archive builds...") isn't lined up on the left margin with the tiles below. Also, see my comment on #115 about standardizing the tile size. Finally, Zeplin has two additional "stacked" and "staggered" cards beneath both of the featured cards (see picture)
<img width="363" alt="screen shot 2018-10-24 at 3 01 12 pm" src="https://user-images.githubusercontent.com/22945600/47454641-b0274100-d79d-11e8-9f34-7d083cd80cd5.png">
- **Updates tiles:** On Zeplin there is no drop-shadow for the smaller white square, and the larger square is presumably entirely gold and changes to entirely melon on hover, right? On the test site only the drop-shadow changes from transparent white to melon. Here's a screenshot from Zeplin.
<img width="304" alt="screen shot 2018-10-24 at 3 02 33 pm" src="https://user-images.githubusercontent.com/22945600/47454887-55dab000-d79e-11e8-937f-6aede2d635d7.png">

**Comment by rlskoeser** [comment]
@mnaydan had to check out the parallax on my phone when I saw your comment - you're right, that is very cool!

**Comment by thatbudakguy** [comment]
quick notes on the stacked card style & update tile style: these differences from the spec are intentional and I'd like to hear people's thoughts on them.

- I did write a "stacked card" style so we have it if we need it, but the stacks don't work as well on mobile (they tend to extend off the screen) because they don't technically count as part of the card width. I could revisit it, but the cards will probably need to change dimensions in order to align correctly.
- I also think the stacks are confusing from a design perspective because they suggest a "collection of collections" or similar - it makes more sense to me to just unify the representation of collections and use the same card style as they appear on the collections list page. making them a fixed size as @mnaydan mentioned should help with this too.
- For the update tiles, changing the entire background to melon looked jarring to me, creating kind of a "flashing" effect. I added the shadow so that the "paper" was accentuated in a manner similar to all the other cards, and the melon color was used as a border in the same way.

definitely not wedded to any of these ideas, just wanted to see what people think.

**Comment by mnaydan** [comment]
Thanks @thatbudakguy, hearing your thoughts on this is really helpful!! I totally agree with you re: the stacked card problem. I agree that using the simpler card style is better--and fixing the size issue will help.

For the update tiles, we might have to loop Gissoo in? I can totally see how it would create a flashing effect, changing the color field on hover. On Zeplin it looks "happier" because the stable design shows the brighter melon color; having that much stable gold on the actual design I think makes it look sad/drab, and I think the gold actually clashes with the melon when they're up against each other (i.e. when the drop shadow changes to melon on hover). It also feels like too many layers to have the background square, the paper, and the drop shadow. I'd almost rather just get rid of the background square and have it behave like the others. Changing the stable gold to stable melon would be confusing because the melon rn is only used for hover, right?

**Comment by thatbudakguy** [comment]
@mnaydan right; it's used to indicate hover currently. I'll see if I can get Gissoo involved, she probably has ideas.

there is also the other style of updates card that's in [the design](https://zpl.io/aMdoQXm)...it was never clear to me what those were supposed to be, but we could just use them as the default style, since they're so much simpler? Maybe on that version on hover the title text could change from the dusk color to melon and leave it at that?

**Comment by mnaydan** [comment]
@thatbudakguy I think that using the simpler one as the default style would work better. Changing title color on hover would be fine. Or we could do a thin bar of gold-to-melon color across the top for consistency with the other elements on the page, like below. Whatever you think works best, I think either would be fine.
<img width="323" alt="screen shot 2018-10-30 at 12 41 41 pm" src="https://user-images.githubusercontent.com/22945600/47735244-8b6e1600-dc42-11e8-8e00-53ab0bac5112.png">

**Comment by mnaydan** [comment]
For desktop:
**Logo:** In GD's design the pink is on the left, and the teal is on the right. On the test site it's reversed. Since "About" (left) is pink and "Collections" (right) is teal it might make sense to fix this. The favicon will need to be updated, too.
**Body text width on homepage:** The width is defaulting to the widths of the other content pages but on GD's design it extends further, just past the editorial and collections headers. This will make the text overlap more with the prosodic symbols, which brings me to...
**Prosodic symbols** in the bg appear much bigger on test site than in GD's design and consequently extend lower than on Zeplin (hence the overlap with the content text). I don't mind them bigger but it's creating overlap problems on the content pages and it needs to be consistent across the pages.
**View and search the archive**: text should be bold
**Learn more below**: Can we eliminate it? I mentioned this to GD, it seems like confusing UX because it uses the same symbol as the "About" dropdown (hence would seem clickable), and I don't think it's necessary.
**Content cards**: Why does "What is prosody" just trail off with ellipses and doesn't fade, but "History of the archive" fades? It should be consistent. Probably the same as editorial, which trails if in the middle of a word AND fades.
**Collections blurb**: Is centered on the test site but should be justified left and flush with the width of the cards.
**Collections cards**: These are fading if the descriptions are too long (and I put in the descriptions that we will end up using on the real site). I don't think they should fade at all. Can you write logic to make only the collections cards go as long as the longest description and have all the collections cards match that length?
