### ISSUE TITLE
Style updates: search (archive) page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#112]
## testing notes
**designs**
[desktop](https://zpl.io/bLxAOGB) / [tablet](https://zpl.io/agr04BA) / [mobile](https://zpl.io/brlZNq7)

includes search results and overall look of the page. doesn't include sorting/pagination (#123) or the form (#163).

**Comment by mnaydan** [comment]
1. "Archive" header is supposed to be SemiBold (600?). It's at 700 right now. The color is supposed to be #444768 but right now it's black.
2. GD's design has more cushion space between author and publisher so that it looks less scrunched.
3. GD's design has just a bit more cushioning on the bottom of each result tile.
4. GD has the default sort option (and I'm guessing, whichever one is selected) as bold ("Title A-Z"); right now it's regular.
5. FYI, the "See more details" is wrapping on a 13" Macbook. (I think this is fine but letting you know per our discussion about screen sizes.)
<img width="1047" alt="screen shot 2018-12-03 at 4 09 10 pm" src="https://user-images.githubusercontent.com/22945600/49401749-10eb5700-f716-11e8-887f-2671c5d0ad02.png">

Mobile and tablet are fine; "see more details" appears on each tile (which is necessary b/c there is no hover)

**Comment by thatbudakguy** [comment]
6. clickable area for the record should be everything above the page previews; not the blue "see more details link"

**Comment by thatbudakguy** [comment]
updates on this:
1. It shows as `font-weight: normal;` in Zeplin for me, which should be 400. Using 600 would necessitate importing another whole font file just to support that weight, which would be the only place it's used on the site, which seems silly. I changed it to 400 to match spec but could change it back to 700 if we like the bold look more.
2. Added some more padding.
3. Ditto here.
4. We talked about this on the sorting issue; having it repeated bold might be confusing UI so I'm leaving the displayed one normal and letting the selected option in the dropdown be bold.
5. Makes sense given what we learned about 13" macbook screen sizes, but useful to know - thanks!
6. Updated the clickable area of the record, which required a number of changes to the markup. Hopefully that didn't break other things.

**Comment by mnaydan** [comment]
1. I guess the bold does stand out more, and it looks less like "Princeton Prosody Archive Archive" with the header right there when "Archive" is bold. Sorry, was just trying to match the spec, but you're right, the bold does look better.
2 and 3. Looks SOOOO much better with the padding, thank you!!

New questions:
1. I'm confused about having two hyperlinks given that the whole block is now clickable ("See more details" and "Total Results: 8 pages", the latter of which we might change the language of to "View all 8 results" or something like that). Both hyperlinks link to the same page but appear discrete on the list view. Would like to discuss in 12/10 meeting.
2. When the relevance score is showing the Collections tag "drops" down, leading to some results with lots of white space (the Collections tag drops even when the screen is widened for "See more details" to appear on the right rather than below the second column). I don't want to lose the padding on the other results, because it looks so much better. If this is only an issue for logged-in admin, I don't care about it, but wanted to see what you thought--would it be an issue if we the relevance bar on frontend (and maybe that's an argument for not adding the relevance bar)?
<img width="1096" alt="screen shot 2018-12-10 at 3 03 11 pm" src="https://user-images.githubusercontent.com/22945600/49759219-0b9a8900-fc8f-11e8-9b3d-ab21b28613e7.png">

**Comment by mnaydan** [comment]
Archive Archive Archive is eliminated (looks so much cleaner!), wording has been changed to "[#] matching pages" and de-hyperlinked, and I'm pretty sure this spacing issue is only for logged in admins, so all looks good!
