### ISSUE TITLE
Style updates: view digitized work page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#117]
## testing notes
**designs**
[desktop](https://zpl.io/2Gz5L6Y) / [tablet](https://zpl.io/bAvMzPP) / [mobile](https://zpl.io/VQqwrzA)
## dev notes
- [x] table headings should be vertically aligned to top to match values
- [x] collection badge should be muted & noninteractive

**Comment by mnaydan** [comment]
- Fonts and everything look right. Looks beautiful on the iPad and iPhone!
- Minor issues: 
(1) On desktop and iPad the secondary title appears to be centered against the label "Secondary Title" instead of justified with the first line of the text and then just cascading down. 
(2) On iPad and iPhone it doesn't have the Added and Last Updated fields like it does on the desktop--just checking if that's intentional.
- Two bigger questions: 
(1) Could you make the collections "badge" the text color like you did on the result list view? Also there should be no interaction on hover/click.
(2) Meredith had expressed concern about the prominence of the Hathi button but I don't think the design was ever changed to reflect this. This might be overstepping but something like "hvd.hwjlqk (Full Text)" in gold might be more subtle, keep users within the PPA site, and still clearly announce itself as a URL. Happy to talk about this more.

**Comment by thatbudakguy** [comment]
@mnaydan great feedback, thank you! I think (@rlskoeser can probably confirm) that the Added and Last Updated fields will only display if you are logged in - my guess is you're logged in on desktop but not on iPad/phone, which is why they didn't show.

**Comment by mnaydan** [comment]
@thatbudakguy *facepalm* doy, thank you for explaining that to me.

**Comment by thatbudakguy** [comment]
left the hathi buttons alone for now pending some design discussion, but the other issues on this should be fixed.

**Comment by mnaydan** [comment]
Fine on tablet. Secondary titles are now correctly aligned with label and cascade down.

On mobile the main title does not line up with the margins of the rest of the information as it does on tablet and desktop.

On desktop, tablet, and mobile, there is still interaction when you touch/click. There's a gold shadow that appears inside the rectangle.

**Comment by mnaydan** [comment]
Margins good on mobile. No interaction anymore across devices. Good to go.
