### ISSUE TITLE
Add a "jump to top" button on search results

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#121]
## testing notes
**design**
[desktop](https://zpl.io/VOmGWZY) - visible on the right side a bit down the page
![screen shot 2018-11-15 at 2 18 40 pm](https://user-images.githubusercontent.com/4924494/48576002-6257b180-e8e1-11e8-9c0d-dd50d92b3128.png)

- this should appear about 3/4 of the way down the page on the right side on both the search/archive page and the item detail page.
- clicking it should take you up to the top of the page.
- on large screens, it should go out past the edge of the search results a little bit so it doesn't cover them up.

**Comment by mnaydan** [comment]
All good! 

- Appears in the proper place on main Archive and item detail pages, and only those pages.
- Clicking it is functional on both pages.
- On larger screens (including my 13") it goes past the side a bit so that it's out of the way. On smaller screens and tablet/mobile it does cover up the results but you can work around it.
