### ISSUE TITLE
As an admin, I want to generate a CSV report of materials on the site so that I can do analysis with other tools such as OpenRefine to analyze collection assignment. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#13]
## Notes for testing
- Should see a download CSV button on the digitized works list page
- Make sure it includes all the information you expect
- Please test after adding some items to collections; test with at least one item in more than one collection

## Notes for Development
- [x] view to export all works and all metadata fields from the database
- [x] Customize the Admin list view to add a link to download the data
- ~Restricted to admins; possibly create a new permission for this?~
- [x] Unit tests
- [x] include collections

**Comment by rlskoeser** [comment]
@meagan1019 we had a open question about whether or not this view needed to be restricted in any way.  There's no sensitive data in the export, so I don't think there's any need - what this means is that a user who is not logged in could get the CSV file if they knew the url (although we're not linking it anywhere that they would see it).

**Comment by meagan1019** [comment]
@rlskoeser this seems fine to me to leave open. I could actually see how giving a well educated scholar and familiar user the link might be helpful in the future as we continue to curate the Archive.

**Comment by mnaydan** [comment]
CSV does not include all of the categories listed in django admin (page count, date added, and date updated.) It does include a Collections column even though that's not viewable on the admin interface (we would like Collections to be viewable on the interface.) Items belonging to more than one collection include both collection categories in the CSV, separated by a semicolon.

**Comment by rlskoeser** [comment]
@mnaydan @meagan1019 do you want page count, date added, and date updated in the CSV?  My understanding was that we only wanted metadata, which is why I didn't include them - but it's not hard to add them if it would be useful.

Does the semicolon for multiple collections work for what you need, e.g. in OpenRefine?  Let me know if you prefer a different approach.

**Comment by meagan1019** [comment]
The semicolon is fine to me; you can always search and replace as a "|" or something that wouldn't be in a long title in Excel if you ran into open refine issues. I do think that it would be helpful, if easy, to have the page, date added, date updated columns if it is easy to add. What I think would be more helpful is to also have the Hathi Catalog Record number (i.e. 001903099 @ https://catalog.hathitrust.org/Record/001903099) for uc1.$b31635 @ https://babel.hathitrust.org/cgi/pt?id=uc1.$b31635;view=1up;seq=11). I'm now noticing that none of the entries have the Hathi Catalog ID and that is a HUGE error on my part. Is it possible to add?

**Comment by rlskoeser** [comment]
@meagan1019 can you explain a bit more about the Hathi Catalog Record number?  What it is, why it is important for you, how you use it?  We can certainly add it at some point, but I would recommend we not hold up the current features to add it - unless it is essential for doing the work of creating and curating collections.

**Comment by rlskoeser** [comment]
@meagan1019 it's trivial for me switch the semicolon to a `|` now while I'm making other edits if you prefer that.  I tested with OpenRefine and it looks like the 'split into multi-valued cell' works fine (it lets you specify what character you want to split on), but I will go ahead and remove the space between the semicolon and the next name, just to avoid any potential for whitespace discrepancies.

**Comment by meagan1019** [comment]
Semicolon is fine then! And eliminating the white space is a great idea. Adding the slack convo here about catalog id as I'm back on my computer: 

The catalog number is how Hathi determines whether the volume is part of the same collection. For example two digitized works will always have an independent Hathi Volume ID (with the host library at the beginning, i.e. nyp.33433067298970@ https://babel.hathitrust.org/cgi/pt?id=nyp.33433067298970) but could share the same catalog id if: 

A) they are multi volume works (v1 of 12 volumes; i.e. The works of the English poets @ http://prosody.princeton.edu/?q=record/008618324 with shared catalog ID 008618324).

B) they are digital duplicates that came from different libraries (i.e. uc1.$b31635 @ https://babel.hathitrust.org/cgi/pt?id=uc1.$b31635 has two digital duplicates, which you can see in its catalog record page @ https://catalog.hathitrust.org/Record/001903099)

The B case matters most to us because this is how we make sure we don’t have duplicate copies of the same work. Of course hathi doesn’t always get this right and many, many digital duplicates have different catalog ids when they should be the same. Because we have manually de-duped the current archive before the rsync, this shouldn’t matter to the website now, but it will be greatly important to have built in so that when we do add more works via bulk import we can make sure we don’t add in digital duplicates.

**Comment by rlskoeser** [comment]
Updated the CSV export to remove the space between collection names (still separated by `;`) when there is more than one, and to include page count and date added and updated.

I tested in OpenRefine, and the date format I'm using isn't automatically recognized with the "common transforms -> to date" option, but it does work with this GREL syntax:
```
value.toDate('y-M-d H:m:s')
```

**Comment by mnaydan** [comment]
CSV export now shows page count, date added, and date updated. There is no longer a space between collection names (still separated by ; ).

**Comment by meagan1019** [comment]
@rlskoeser should we create a new ticket to have the collections column viewable in digitized work list view on the admin site? other than that this ticket should be good to close

**Comment by rlskoeser** [comment]
@meagan1019 yes, please create a new ticket for that.  Also let us know what, if anything, we should drop anything from the current list view to make room for adding it.

**Comment by meagan1019** [comment]
@rlskoeser what is the limit of columns? thinking how to prioritize since we'll also be adding catalog id to the view

**Comment by rlskoeser** [comment]
@meagan1019 there's no strict limit, it's up to you.  We can add more, it just is likely to get unwieldy at some point, especially depending on the monitor size you're using. I just checked, and there is a minimum width for the list - so with smaller monitors you just won't see the fields on the right without scrolling over.  That probably means it's ok to include more fields if you want them, but the order may become more important.  Rearranging the order is trivial, so please let us know where you want collections to show up (and if you want any other changes to the order).
