### ISSUE TITLE
As a user, I want keyword searches to prioritize matches in the author, title and public notes fields so that I can easily find works using keywords.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#149]
## notes for testing
Search has been reconfigured so that matches in title, author, and editorial notes result in a higher relevance ranking (current boost levels: author^20, title^10, notes^10). This change in search configuration impacts all keyword searching, so re-testing existing search functionality with this change will be important.

A score field for logged in users has also been added to facilitate this. A keyword match will markedly boost a score, a phrase match (`advanced elocution` vs `elocution`) will do so even more.

- to test the new relevance ranking, try the following searches in the "keyword or phrase" input, and make sure you have set sorting to relevance:
  - search on terms that will match author names; to check relevance against text matches, try search terms like *blood*, *wood*, *cone*, *french*. Items where the author matches should be listed before items with text only matches
  - similar for terms in title: matches in titles are considered more relevant than matches in full text; possible search terms to try *prosody*, *discourse*; title is not boosted as much as author, so author matches should show first; maybe test by search terms like *english* which appear in both author and title fields
  - similar for terms in editorial notes: matches there should be more relevant than elsewhere
- to test that the updated search configuration hasn't broken anything:
   - test that searching on all fields included in keyword search still works (book metadata and page content; specific fields are source id, title, author, notes, publication date, enumcron, publication place, publisher)
    - test that you can still use exact phrase and boolean searches, and they work properly (note that the change in configuration means it's harder to get a syntax error, e.g. with an incomplete exact phrase, because the query parser we're using is more error tolerant)
    - test that pages with matching text still display with the book metadata and terms are highlighted
    - test that searching on a term that appears in the full text of a book but nowhere in the metadata displays the book record with matching pages
    - test that phrase matching boost scores as well (i.e., `advanced elocution` vs just `elocution`)

## Dev notes
From 2018-11-14 meeting notes :
- Title (but boost less)
- Author
- Notes

**Comment by mnaydan** [comment]
Mostly everything with the relevance ranking looks good (I tested everything you suggested, and more--thank you for the detailed notes!) My only question is whether exact matches in the title should be prioritized over stemming searches even without quotes? For example, searching "lives" yields results with "living" and "live" before some results with "lives" in the title. Don't know if you have control over this or not--might just be Solr.

Boolean and exact phrase generally appear fine. Metadata and full text generally appear searchable. Some search issues that might be broken:
- Searching a source ID does not work in the backend the same as the frontend--on the backend, it yields the unique result only, searching mdp.39015016748504 as a unit. On the front end, it yields results with the letter combination ("mdp") and even when you put quotations around the source ID seems to be searching the numbers as discrete units (a search of "mdp.39015016748504" yields 614 page hits).
-Enumcron is also a little tricky—searching July-Dec 1890 (no quotes) yields only 1 result in the admin, but 3,000+ in the frontend (it’s searching the months separately as keywords) and searching with quotes yields no results, unless you put in the entire (rather than partial) enumcron for the result I was trying to get (“v. 38 (July-Dec 1890)” yields njp.32101065266304, but "July-Dec 1890" yields nothing). The prod site yields the enumcron result first even though it is also searching the months separately. 
-When I search advanced elocution (no quotes) the first result is "Exercises on etymology" (njp.32101074757137) because "elocution" is in in the author metadata field (Graham, William, teacher of elocution). The number 2 result therefore gets booted from number 1 ("Advanced elocution" (uc1.$b293521)) despite being more relevant to the phrasal search. Might just be a quirk of the new boosting--you get uc1.$b293521 when you use quotes around "Advanced elocution." 
-When I searched “iamb meter pentameter”~50 the first result only highlighted the word meter on the keyword detail page, even though pentameter and iamb also appeared in the results. Is this syntax not correct?

@bwhicks I'll let you decide whether to close or not--the source ID at the very least seems like a bug that needs fixing, and maybe the proximity search.

**Comment by rlskoeser** [comment]
Responses to what you've found based on my research so far:

1. You're right, it does seem to be tokenizing the id. I'm not sure why this is - we have it configured to use the standard tokenizer, which the documentation says should _not_ tokenize on a period that isn't followed by a whitespace. I can investigate more on that one. I was able to confirm what you said in your notes.  I also discovered that the search supports field searching within the keyword - e.g., try `srcid:mdp.39015016748504`. Do you want this capability? What field name would make sense to you for this? Would you prefer `srcid` or `source_id` ?
2. enumcron is currently configured as a string field and not text, which means it doesn't get tokenized the way other fields do. (I was somehow thinking of it as something for display, not for search!) That should obviously be changed. Also available in the keyword input, e.g. `enumcron:"v. 38"`
3. Currently author is boosted more than title, based on comments from MM when we first discussed, but that's easy to revisit. Do you want to try having them boosted the same? Should title be boosted more than author?
4. I think proximity search is handled automatically now - I'll see what I can share with you in terms of documentation for how phrases are handled and what we can configure. Basically, it's always doing a secondary proximity search and increasing relevance when items match, and we can configure how big the range on that proximity is.

Regarding exact match vs. stemmed term - I looked and found something I can try that might have an impact on that (search on both the tokenized and untokenized version of the field).

Regarding the fields that can be used in the keyword search, I think these are the ones that make sense:
* srcid (preference on how to label it? I believe we can easily alias these)
* title
* subtitle
* enumcron
* author
* pub_date 
* pub_place
* publisher

I can restrict it to make sure only these are exposed, so we don't include things we don't mean people to search on. Let me know if you don't want any of these.

**Comment by rlskoeser** [comment]
More updates.

1. According to the solr docs, the source id shouldn't be tokenized on `.`, but clearly it is getting tokenized. Is it sufficient if we can have the record with that id show up first?
2. I'm going to change how enumcron is indexed, local tests indicate that addresses some of the problems you're seeing. (will require a full reindex, unfortunately)
3. Based on your comments, I switched title and author to be boosted at the same level - I think it's behaving better, but there may be searches I'm not thinking of where this is a problem.
4. Here is documentation on [extended dismax query parser](https://lucene.apache.org/solr/guide/6_6/the-extended-dismax-query-parser.html) - the top has a summary of how it works. It says that full lucene syntax is supported, so the proximity search ought to work. I tried some simpler cases, which I think shows it working ok: `"questions purpose"~10` shows the highlighting you would expect. I suspect the highlighting doesn't behave the same way as the querying, and 50 is probably too big a range to display in the one snippet.

**Comment by mnaydan** [comment]
Thanks for the updates! My list numbers below don't match yours (I'm responding to both your comments at once since they overlap)
1. As we discussed in the meeting I think that fielded searching for power users is a great capability--I would want to be able to search all of those fields you listed, and I don't see any problem with letting users do so. As a lay person "source_id" makes more sense to me, especially since pub_date and pub_place already use underscores.
2. RE: title v author relative boosting. I think the case I tested is a fringe case. My issue was that "elocution" was included in the HT metadata under the author field (Graham, William, teacher of elocution), but obviously isn't an author name. A brief look in OpenRefine suggests that this is pretty uncommon. I need to think more about whether making title and author even will be a problem.
3. The highlighting for the proximity search case I tested is working now.
4. I think if you can get the source ID record to show up first (and your time would be better spent elsewhere than fighting with solr on this issue) that would be sufficient. Does it still get tokenized if you field search source_id?

**Comment by rlskoeser** [comment]
Updated the test site with my latest Solr config and index changes. 

Dispensing with numbers because, as you said, they aren't matching up very well anymore!


- Try the search with the current boosting.  I've added subtitle (which I think we'd missed), although in the version that's on the test site title and subtitle are weighted evenly, and I'm guessing title should have priority. Regarding boosting on title vs author, I think the question is: if a search term matches both author and title, which record would you want to see first?
- Title and subtitle should now match on unstemmed versions of the words first (i.e. **lives** or **living** before **live**); it has occurred to me we should add similar logic to the title and author fields, but I propose we create a separate issue for that and prioritize against other work.
- I have changed how `enumcron` is indexed - searches on this field should work better
- Searching by hathi id should result in that record showing first (when you sort by relevance).  If you search with the `srcid:` notation, you should get only one record (term does not get tokenized).
- I agree with `source_id` but have not yet had the chance to implement.  Perhaps we could track that separately from this issue?

**Comment by mnaydan** [comment]
- I do think title should be boosted more than subtitle. I hope that's easy enough to change?

- Re: title v. author boosting, thank you, the way you asked that question is really helpful. I searched "Johnson", and I am getting works _about_ Johnson (works with Johnson in the title) first, and I think I _would_ expect to get works _by_ Samuel Johnson first (and all clustered together, followed by works _about_ SJ with his name in the title). Sorry for going back and forth on this. Again, I think the "elocution" example I tested was a fringe case. So maybe boost author more over title? 

- Re: the aggregate question, it looks like things with metadata hits are sorting before things with full-text only hits, which is what we want. The full-text only hits are where it might get dicey? Some works with higher max relevance scores are appearing _below_ some works with lower max relevance scores (on my search of **hood**, max 5.1 appears before max 7.5). But as I said on Slack, I think it is working well enough that it is not a priority right now.

- Tested the stemming issue with **lives** and **lives** is appearing first, but then I get **Living**, **Live**, **Live**, **living**, **living** **living**. Is it case sorting? I tested with **classical** too and it's giving me "classical" first, but then I get some results with **classic** early in the title instead of one more results with **classical** later in the title, which is appearing lower on the list.

I thought about whether to integrate this logic for author too, but couldn't think when it would actually be a problem? I don't think there are authors with close enough names? And was there another field you think we need to add the logic too? You mentioned title again but it's already working for title and subtitle? I don't think it's a priority unless you have an argument for it. 

- Enumcron is kind of working better. It doesn't seem to recognize whether there is a space between the period or not, whether you use quotes or not ("v.1" with quotes doesn't return results with "v.1" in the enumcron; it returns stuff with **v 1** in the full text). But it works great if you do a fielded enumcron search. I think it's fine as long as we document in the About section.

- Hathi ID search without quotes gives that record first. With quotes OR with srcid: notation you get only one record. (It still tokenizes--it returns 510 matching hits inside the book for instance. But that's fine, I think)

- I will make source_id a new issue now.

**Comment by rlskoeser** [comment]
@mnaydan thank you for your careful testing and detailed notes! 

My understanding of what is left to be done, please confirm:
- boost title more than subtitle
- boost author more than title

I'm not sure what's going on with the stemming (and not sure I'm duplicating it); do you need anything more on it or do you think it's good enough?

**Comment by mnaydan** [comment]
Yes! Thank you for summarizing. I think the stemming is good enough if you do. So just those two things, unless you think we need to add the stemming logic to author or another field.

**Comment by mnaydan** [comment]
Title is now boosted more than subtitle! (tested with "rules")
Author is now boosted more than title! (tested with "Johnson" and "elocution")
