### ISSUE TITLE
As a content editor, I want to list people who contributed to the project so that I can give credit to everyone who was involved in it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#160]
## testing notes
**designs**
[desktop](https://zpl.io/bz1Bqgl) / [tablet](https://zpl.io/VKonDRP) / [mobile](https://zpl.io/29PAwnB)

you'll need to create a new page in wagtail that has the special type "contributors page". when that's done, you can add new the "person" block to the "contributors" and "board" sections of the page to populate it with people.

**Comment by mnaydan** [comment]
Works well on backend! Was able to add people and their titles/descriptions to snippets, and then add the people to the contributor page. We made the body optional for contributor page (since MM revised the content it will be all tiles).

Frontend looks good after we made the following changes:
We decided to wrap long titles for desktop because they were running together on 13" Macbook.
We also pushed an update for hyperlinked tiles to open in a new tab.
