### ISSUE TITLE
Style updates: collections page

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#169]
## testing notes
**designs**
[desktop](https://zpl.io/a8PLdvw) /  [tablet](https://zpl.io/2EKL79y) / [mobile](https://zpl.io/bLxeXnG)

**Comment by mnaydan** [comment]
1. It looks like the transparency of the prosodic symbols is going in front of the title ("Collections") and body text, instead of the heading and body text being fully opaque in the frontmost layer (this impacts readability a bit). This is true across content pages. 
2. As on #107, the collections cards are fading/cut off if the descriptions are too long (and I put in the descriptions that we will end up using on the real site). I don't think they should fade at all. Can you write logic to make only the collections cards go as long as the longest description and have all the collections cards match that length?
3. As on #62, there should be a bit more cushion space between the header and the landing page title.

For tablet/mobile only (in addition to the above):
1. There is a gray bar at the bottom of the cards (see screenshot on #107 https://user-images.githubusercontent.com/22945600/49307780-396c1a80-f4a4-11e8-9f1f-6d8a6a32e620.jpg)

**Comment by mnaydan** [comment]
1-3 are fixed! The extra padding looks a lot better, thanks for doing that. 

I hadn't realized that the card titles aren't bold in GD's design, but I think I actually like it better bold so I'm fine with leaving it.

On tablet, the card isn't long enough for the Typographically Unique description because of the way the title wraps, but I'll note that on #187 as I don't think it should keep us from closing.
