### ISSUE TITLE
Style updates: error pages

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#172]
## testing notes
**designs**
404 [desktop](https://zpl.io/aN9AmZ9) / [tablet](https://zpl.io/bA4X7Ex) / [mobile](https://zpl.io/bz1GqW3)
500 [desktop](https://zpl.io/2jPoNMW) / [tablet](https://zpl.io/aBqlRNK) / [mobile](https://zpl.io/2ylQqy9)

To test the 404 (not found), just go to a random nonexistent url, like: https://test-ppa.cdh.princeton.edu/foo/
To test the 500 (server error), go to https://test-ppa.cdh.princeton.edu/500/ to cause an error.

note that we're using gentium for headers which isn't reflected in the designs. the designs are also using a semibold weight for the error text, which we also aren't using - I can make them fully bold if we want them to stand out more.

## dev notes

**Comment by mnaydan** [comment]
1. (For both 404 and 500 pages) In Chrome for desktop (and Safari for tablet/mobile) the logo is way too big, and depending on which logo iteration you get, the text is misplaced in different ways.   
<img width="1135" alt="screen shot 2018-12-14 at 1 18 16 pm" src="https://user-images.githubusercontent.com/22945600/50020391-cc787a80-ffa3-11e8-8ce2-fd702a9865fa.png">
<img width="1057" alt="screen shot 2018-12-14 at 1 19 46 pm" src="https://user-images.githubusercontent.com/22945600/50020396-d13d2e80-ffa3-11e8-8a2f-2c80de2f3ad7.png">
2. The top bar above the header is pink right now and is supposed to be black.
3. The "E" in "Server Error" needs to be capitalized.
4. The "History of the Archive" etc line in the footer has disappeared on the 500 page only in FF and Chrome.

**Comment by mnaydan** [comment]
The 404 and 500 pages look good now across browsers and devices. Thank you! 

@rlskoeser did note on Slack that the About dropdown doesn't render on the 500 page. Would it be enough to make the "About" unclickable (pointy arrow instead of mickey mouse) and the arrow un-flippy? My impulse as a user if I get a 500 error is to go to the home page, not the about page, anyway.

I'm going to close this issue though and if we wanna make the About issue a separate issue we can.
