### ISSUE TITLE
Lazy load search result preview images to improve performance

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#176]
## Notes for testing
- Do an archive search for something with page image matches. As you scroll down the page, you should briefly see a placeholder and then the hathi image should load. 
- Also test that it works the same way when searching within a single work.

## dev notes
Here's a [relevant MDN tutorial](https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Loading). We may need a placeholder image to make this look nice.

**Comment by rlskoeser** [comment]
Still needs:
- [ ] CSS transition for placeholder to image
- [ ] unit test for lazy loading js code (?)

**Comment by mnaydan** [comment]
Huh, this works correctly searching WITHIN a work, but not on the main archive page. The main archive page isn't loading the thumbnails at all, even after waiting a bit:
<img width="1038" alt="screen shot 2019-02-26 at 4 38 56 pm" src="https://user-images.githubusercontent.com/22945600/53448374-3f12c700-39e5-11e9-9600-3853b7f6d77c.png">

**Comment by thatbudakguy** [comment]
Should be fixed now, thanks @mnaydan !

**Comment by thatbudakguy** [comment]
once more with feeling!

**Comment by mnaydan** [comment]
Lazy load is working on all desktop browsers (Chrome, Safari, FF) on initial search results page and item detail page. Lazy load is not working on tablet or mobile--all you get is the placeholder image, unless you refresh the page. Since I don't have time to test on Monday, I'm fine with letting dev team sign off in this issue once it's fixed, since they can reproduce the problem on their tablet.

**Comment by thatbudakguy** [comment]
Upon further investigation with @rlskoeser , safari (both on desktop and mobile) is requesting _both_ the 2x sized and thumbnail sized images, which leads to severe throttling (especially on mobile/tablet).

We might be able to resolve this using `<picture>`; making a note to myself to try that out.

**Comment by rlskoeser** [comment]
Tested the new version on QA and it's behaving better than it was - images load in seconds (sometimes many) rather than minutes. People using iPads will probably get throttled faster than those on other devices, since it has the bad combination of retina screen + no lazy loading (due to no observer support).
