### ISSUE TITLE
Handle invalid search cases in form UI

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#177]
## Notes for testing
The new query parser we're using (we switched when we enabled field boosting) is much more error tolerant; the only way I've been able to trigger this problem is a solr connection error. When you're ready to test, ask the dev team and someone can temporarily change the test site config so that it will fail connecting to Solr.

When entering an invalid search such as "/", some aspects of the form UI break:
![screen shot 2018-11-28 at 11 27 55 am](https://user-images.githubusercontent.com/4924494/49166118-b199db00-f300-11e8-91cb-bc500a2e1382.png)
![screen shot 2018-11-28 at 11 27 59 am](https://user-images.githubusercontent.com/4924494/49166126-b3fc3500-f300-11e8-8e60-37e7a7babdd3.png)

## dev notes
just don't display pagination if there is an error.
if there are no results, should read "displaying zero items" or similar.

**Comment by rlskoeser** [comment]
This will be less of a problem when we switch to the new field boosting logic, since `edismax` is much more tolerant of syntax errors - I haven't yet been able to figure out anything to trigger one, actually. But we should probably still correct it? (Although it won't be testable if we don't have any known searches that trigger it)

**Comment by mnaydan** [comment]
RSK temporarily changed the Solr config to trigger the old error and the UI no longer breaks: pagination displays and it says "Displaying 0 digitized works".

If you enter "/" it returns 214 matching pages on the first list result with thumbnail (but no snippet) and when you click to the item detail page you get an error that says "No matching pages." But since the UI isn't broken and this is such a fringe case I think it's fine.
<img width="1070" alt="screen shot 2018-12-11 at 4 38 24 pm" src="https://user-images.githubusercontent.com/22945600/49832145-dd3aad80-fd63-11e8-8eb8-675756cfb638.png">
