### ISSUE TITLE
Tablet/mobile style issues

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#187]
Catch-all for style issues deemed minor enough that they weren't required for closing the other style tickets.

**Comment by mnaydan** [comment]
**Mobile**:
1. Collections tiles not aligned correctly--left margin is too tight, right margin is too wide.

**Comment by rlskoeser** [comment]
The advisory board heading on the contributor page is smaller than individual contributor titles which is jarring to me because I know it's supposed to be a section heading; likely confusing to others. In the design it looks like it is the same size and there is more space above it.
<img width="345" alt="screen shot 2018-12-21 at 11 11 56 am" src="https://user-images.githubusercontent.com/691231/50351869-72caff80-0511-11e9-8a99-2d8ec012eaf6.png">

**Comment by thatbudakguy** [comment]
need to re-evaluate how many of these are still a problem.

**Comment by thatbudakguy** [comment]
@mnaydan do you have a sense of how many of these were captured by the more specific issues we're testing now? it seems like at least 5, 6, 8, 9, 10 for mobile and 2 for tablet are mentioned specifically in other issues.

some of them might no longer be issues as well, not sure

**Comment by mnaydan** [comment]
For mobile
1 is still a problem (collections tiles not centered on main page) but not important enough to me if you don't have time
2 I don't care about anymore
3 is still a discrepancy b/w the designs and prod but I don't care about fixing it
4 is fixed
5 and 6 are captured in other user stories
7 is so minor I don't care
8 is captured in another user story (and fixed)
9-10 are captured in other user stories

I don't have my tablet with me to check. Will get back to you on this.

**Comment by thatbudakguy** [comment]
altered the font size slightly for these cards so *hopefully* they should all now fit - I realized there are collections in here that I don't have locally to test with because they were created recently, hence the discrepancy

**Comment by wafaisfahany** [comment]
All solved I believe - unless @mnaydan  still cares to fix 1,2 and 7?
