### ISSUE TITLE
Styles: image captions

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#209]
## testing notes
**designs**
[desktop](https://zpl.io/aXkRDrx) / [tablet](https://zpl.io/aXkRZkM) / [mobile](https://zpl.io/bA4397P)

you can test it by adding an image to an editorial in wagtail and entering a caption along with it.

**Comment by mnaydan** [comment]
Can add images with and without captions in Wagtail now. 

But @thatbudakguy I realized that the caption style looks kind of weird if it's relatively short? Do you think centering it (instead of justifying left) would be an easy fix? 
<img width="943" alt="screen shot 2018-12-14 at 11 52 49 am" src="https://user-images.githubusercontent.com/22945600/50016317-d2b42a00-ff96-11e8-9878-3bca17517e8d.png">

**Comment by thatbudakguy** [comment]
It's tough, right? short captions probably look better centered, but any more than one line and they probably look better justified left. Maybe we should assume that most captions will be <1 line and go with the center alignment?

**Comment by mnaydan** [comment]
I would think that most captions would be around the length of that Milton example (<1 line) so I agree, let's go with center alignment.

**Comment by mnaydan** [comment]
@thatbudakguy did you center the captions? Or did we change our minds? They are all still left-justified for me across browsers and I hard refreshed and added new posts in test.

**Comment by thatbudakguy** [comment]
@mnaydan agh, I'm sorry!! I definitely did the opposite of what we said. thanks for being vigilant. fixed now

**Comment by mnaydan** [comment]
Centered now. This looks a lot better! Thank you!
