### ISSUE TITLE
Advanced search appears briefly on page loads

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#224]
when loading the search interface for the first time or paging through search results, the advanced search will briefly flash open and then hide itself. this shouldn't be happening, as it defaults to `display:none;`.

**Comment by thatbudakguy** [comment]
this is because of what we're doing with the `no-js` forms styles:

1. the page loads the main stylesheet, which sets the `.advanced` portions to `display:block;` if 'no-js' is applied
2. the DOM is rendered, with the 'no-js' class by default, which means the advanced search always starts visible
3. the DOMContentLoaded hook fires and the '.no-js' class is removed, hiding the advanced search

there might be a clever way to mitigate this, but I haven't thought of one. how important is it?

**Comment by rlskoeser** [comment]
Wow, thanks for tracking that down - totally makes sense, now that I think about it. I'll think about whether there's another approach to handle this without that side effect....

**Comment by rlskoeser** [comment]
I did some research and found this https://stackoverflow.com/questions/218162/embedding-extra-styles-with-noscript

Seems like the best two options are either to:
-  include `modernizr` in the very beginning of the head (this will add a `js` class, sounds like it will remove the `no-js`)
- use a `<noscript>` in the head with our no-js styles, which is apparently supported now

**Comment by rlskoeser** [comment]
Should be addressed by noscript style changes included in #263

**Comment by mnaydan** [comment]
Advanced search page is no longer flashing. Tested first arrival on archive page and also clicking back to it after viewing a result. The slightly weird thing is that the "Advanced Search" title shifts slightly to the right upon load because it briefly shows the red dot denoting active fields, then the red dot disappears and the title recenters. But this is a different issue and nitpicky enough that I'll close.
