### ISSUE TITLE
As an admin, I want a "Collection" column viewable on the "Digitized works" page so that I can easily see what collection(s) an item belongs to.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#25]

**Comment by bwhicks** [comment]
## Testing notes
Suggestions
- [ ] View the change_list and there should be a collection column for any item which has that set (filtering by collection would be a quick way to see it)
- [ ] <ultiple collections should be denoted by a comma-separated list.

Known limitation: I did not add sort by collection because it would not be meaningful because Django admin does not provide a custom method to sort such a listing based off a many-to-many relationship.

**Comment by mnaydan** [comment]
Collections column appears in list view. Items belonging to a collection display that collection name. Items belonging to multiple collections show both collection names separated by a comma. Filtering by collection works.
