### ISSUE TITLE
Site flashes gray in Chrome when toggling between tabs after PPA tab is inactive for a certain period of time

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#250]

**Comment by bwhicks** [comment]
After some investigation, this issue seems related to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=933801&q=tab%20switching&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

Sadly, it was just reported three days ago and is undergoing triage. My guess is that the JS draw is getting called on tabbing over, which shouldn't be happening, but it's causing a gray frame while everything is being redrawn. (The Chrome profiler actually locks-ups when trying to observe what might be going on. Firefox is showing a pretty long JS spike during loading.)

I'd defer to @thatbudakguy as to whether we can effectively do anything about that but this is probably going to be more rather than less difficult to fix. However, reporting my poking for the benefit of others.

**Comment by thatbudakguy** [comment]
thanks @bwhicks for looking into this. @mnaydan could you keep an eye out next time this happens to see if it also affects your other (non-ppa) open tabs? I think ultimately it's probably something occurring at the level of the rendering engine and so we can't address it, but it would be nice to confirm that we're seeing the bug @bwhicks identified.

going to close this as wontfix since it's likely not actionable.

**Comment by mnaydan** [comment]
@bwhicks @thatbudakguy interesting... I have been keeping an eye on it since I noticed it in December and weirdly it only happens with the PPA tab for me. But I understand why it's a wontfix for us.
