### ISSUE TITLE
Editorial tile style issues on mobile

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#253]
1. Tile is too large
2. Snippet text is too small
3. Shadow box appears around title when touched
![mobile1](https://user-images.githubusercontent.com/22945600/53106868-ec776d80-3501-11e9-8954-4e90bd23dd96.png)

**Comment by thatbudakguy** [comment]
1. the tile height should match [the design](https://zpl.io/bPvNM9y); since the cards have a uniform height, some of them might appear large because there isn't much content in the body part. I think we did this so that there would be space for both the headline and the body to expand, if necessary.
2. Fixed the font size, which should fill this out a bit more.
3. Unfortunately I can only replicate the gray underline when trying to _drag_ the tile, and only on an iPad (I don't have an iPhone, just safari's device emulator). I added one thing that supposedly could fix it, but I don't have any way of testing (it didn't remove the gray underlines on dragging). If that doesn't work, I'm out of ideas.

**Comment by wafaisfahany** [comment]
1) Gray underline no longer visible on mobile - 
2) No Purple divider between {Editorial card title - date} and {snippet}
<img width="253" alt="screenshot 2019-02-27 at 17 49 58" src="https://user-images.githubusercontent.com/47332262/53528614-21626200-3ab8-11e9-986a-5d7346bbbd5d.png">

**Comment by thatbudakguy** [comment]
I think we decided to not do the purple line in order to save space inside the cards, since we're already cutting it a bit close. @mnaydan will you confirm this is OK?

**Comment by mnaydan** [comment]
@thatbudakguy yes you're right about the purple line. It looks SO much better thank you.
