### ISSUE TITLE
As an admin, I want an easy way to give project team members archive management and content editing permissions so that I don’t have to keep track of all the individual required permissions.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#3]
## Notes for testing
See the notes on #2 - I guess they really belong more properly on this story (the two are related).  I've set the app to automatically create the two groups for you to simplify things.

**Comment by meagan1019** [comment]
I see this isn't ready for testing yet, but as we think through it Meredith and I were thinking how this functionality would be a good place for us to directly rebuild the new collections we want to editorially make. As discussed, Meredith wants to refine new categories for the "collections" and that will take us going through the material and assigning them. We usually do this offline via CSV, but does it make sense to do this directly into the system so that you won't need to batch upload the new collections tags to each volume? Works might have many collections tags (i.e. "Brogan" and "Typographically Unique" and "Grammar"). Let me know what is best, we can always do this via CSV and then add.

**Comment by rlskoeser** [comment]
@meagan1019 my plan was for collections to be edited through the admin site.

**Comment by meagan1019** [comment]
This seems to work well from testing #2!
