### ISSUE TITLE
Upgrade django + wagtail

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#323]
## testing notes
Run through the entire site and check that everything still works properly, including public facing functionality,  wagtail content management, and data work (bulk add to collection, add from hathi, etc).
Additional specific things to check based on changes or new features:
- create a user with view only permissions and check django admin: view user should not have access to add from hathi or bulk add to collection option
- test that the publication date histogram on the archive page displays correctly and updates when you refine your search
- test new and revised wagtail richtext features (blockquote, superscript, subscript, code)

## dev notes
- [x] upgrade to django 2.2 LTS
- [x] upgrade wagtail 2.7

**Comment by rlskoeser** [comment]
I had planned to remove grappelli and update the django admin templates accordingly, but I now think that should be a separate issue.

**Comment by mnaydan** [comment]
Public facing functionality seems to be fine. 
I checked content pages, links (internal and external), and various searches on archive page. On archive page I checked search boxes, limiters, filters, sorters, thumbnail and detail links, as well as search within volume and links to Hathi. I checked the histogram with a few different searches and it displayed correctly and updated to reflect the refined search.

For data work on admin site, everything also seems to be fine. 
I checked adding a new collection, bulk adding items to a collection, adding individual items to a collection, suppressing an item, adding 1 and multiple items from Hathi (including Google and non-Google books), deleting a user, changing user status/permissions. I added a new user with view only permissions and view user does not have access to add from Hathi or bulk add collections.

For CMS, everything also seems to be fine, with a few ticks I'm not sure are related.
I checked editing existing content pages, adding a new editorial child page, editing/adding a new person snippet, adding a new person to the Contributors page, uploading a new image. In the "Rich-text test" post I tested adding all different content types and all rich text options, including blockquote, superscript, subscript, code. All good. The ticks:

- Side-by-side display images isn't working, but I created a bug issue for that #326.  

- The horizontal line is having some problems, too. It's not displaying consistently in the WYSIWYG editor (see under "Rich Text Test section" heading where it disappears after publishing), and the second line I had put in that section isn't showing up on the public site (or it appears to be white instead of dark gray?). @rlskoeser is this a separate issue? 
<img width="310" alt="Screen Shot 2020-01-24 at 2 01 53 PM" src="https://user-images.githubusercontent.com/22945600/73096134-24c1c180-3eb2-11ea-8ca2-c62fb26f1757.png">

**Comment by rlskoeser** [comment]
Strange about the horizontal line... I don't remember touching anything related to the styles, although I guess it's still possible the upgrade could impact them. I'm suspicious, though, since you discovered the other side-by-side image display problem that's already in production. Can you check if the horizontal line is behaving the same way in production?

**Comment by mnaydan** [comment]
It is behaving the same way in production. Second horizontal line in the same paragraph block appears white, and lines will disappear in WYSIWYG editor. I'm going to create a separate bug issue for this, too, and close out since everything else appears good.
