### ISSUE TITLE
As a user, I want to search within a single Gale/ECCO item so that I can find more page results and keywords in context than are available on the main archive search.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#377]
## dev notes
Should work without additional code changes once import and index is implemented. Adding to explicitly track and test.

**Comment by mnaydan** [comment]
I tested a variety of keywords across CB and CW volumes (and checked a couple HT volumes for good measure). Search within volume functions as expected.

However, in testing this issue I discovered that I was unable to yield expected keyword search results for words appearing on pages that ECCO categorizes under "Front Matter" or "Back Matter" in both the main search and search within volume. For example, "bardism" in CW0115966339 yields zero results (the JSON file didn't show any OCR for pages 2-79, where "bardism" occurs). I tested with CB0130984232, CW0103485860, CB0127060085, CW0113494123 to confirm, and the pattern holds across all. We know Gale has the OCR for the Front/Back Matter because they are searchable in Gale's interface. We suspect this is an issue with the API, and Bill is looking into it. 

@rlskoeser, given that this is most likely an issue on Gale's API end, not your code, should I close this issue? Or do you want me to keep tracking it here?

**Comment by rlskoeser** [comment]
@mnaydan I think we should close this issue, since the problem isn't on our end, and existing code will work once they add the missing ocr content into their api. We might want to track it somehow but I'm not sure where!

**Comment by mnaydan** [comment]
@rlskoeser I think it'll naturally be tracked on the excerpts stories - we won't be able to see text snippets for excerpts if there's no OCR.
