### ISSUE TITLE
As an admin, I want to include book excerpts and articles as well as full volumes, so that I can include material that is specifically about prosody from longer works about other subjects.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#393]
## testing notes
- [x] check that you can edit new excerpt fields in the admin interface:
   - [x] item type
   - [x] book/journal title
   - [x] volume
   - [x] original page range
   - [x] page range in source
- [x] check that item type is displayed in the digitized works list view, and defaults to full for all existing content
- [x] test that invalid page ranges are rejected for digital/source pages (try out of order, non-numeric, etc); make sure that multiple ranges are supported as expected
- [x] test converting an existing record into an excerpt: when you save with digital page range, it should recalculate the page total for that item _and_ it should update the index to only include the pages in range.

## dev notes
change digitized work db model as follows:
- [x] add item type (full, excerpt, article); all current content should default to full
- [x] add new fields for book/journal article, volume, page range (actual, for display/citation), image sequence range (for importing the correct portion of a volume from an external source)
- [x] make new fields editable in admin
- [x] include new fields in the list view if appropriate (item type at minimum)
- [x] implement validation to make sure the field we need digital pages field will be parsable

**Comment by rlskoeser** [comment]
@mnaydan what label should we use for the item type of current content, non-excerpts? volume? work? full? (It will only be visible to administrators, I don't think we're using this in the public interface anywhere)

**Comment by mnaydan** [comment]
@rlskoeser full makes most sense to me.

**Comment by rlskoeser** [comment]
@mnaydan let me know if you have any ideas about the field order you'd like or which of the new fields you want on the list view. I was thinking of adding the new item type* field (full/article/excerpt), but it looks like the list view is already pretty full.  Is there anything you don't use that you want to drop? Or should I shorten the width for the date fields?

Also, let me know any preferences for the field order/organization on the edit page.  (If it's easier to think about order/layout after seeing an initial version, we can wait.)

* Wondering if we can come up with a better name than "item type", which doesn't seem quite accurate (at least, not for "full"); extent, maybe? or does item type make sense to you?

**Comment by rlskoeser** [comment]
@mnaydan I'm also wondering if the item type (full/article/excerpt) should be read only – I'm not sure if it will work to change the extent after an item has been indexed.... Although, I guess it if it _does_ work then we might have a solution for the items you said that are already included in full and need to be converted to segments.  I'll leave it editable for now and we can test whether or not it works to change the status and page range of an existing record.  (But let me know if you have any opinions on this.)

**Comment by mnaydan** [comment]
@rlskoeser I don't think page count is essential to see on list view... we could swap that column out? 

For placement: On list view, item type would make sense to me maybe between author and collections columns? And on detail view maybe toward the top after source URL (so that you're primed to know what you're looking at when you look at title and author info below). Do those placements make sense to you? 

I agree that "item type" technically doesn't make sense for "full", but I think that's an intuitive label for me and Meredith at least. I can't think of anything better.

**Comment by rlskoeser** [comment]
Thanks @mnaydan, your suggestions make sense to me, I'll try those out.

If item type makes sense to you two, then it works for me. How do you feel about relabeling "full" to "full volume" ? (If it doesn't bother you I'll leave it; you're the ones who will be working with it!)

**Comment by mnaydan** [comment]
@rlskoeser what about "full work"? "Volume" makes me nervous because of its use in enumcron and multivolume runs. Might just be me, though...

**Comment by rlskoeser** [comment]
Yes, right — volume has other meanings, doesn't it! Full work makes sense to me.

**Comment by mnaydan** [comment]
@rlskoeser the majority of the article/book excerpt works are works that are currently contained in the PPA in full (maybe 300?). Would it be easier for you to take those works out of the PPA, then reinput them as articles/excerpts whose status and page range is uneditable? Even being able to do just that, since I have all the work done already in a spreadsheet, would be hugely helpful and totally change the PPA (for the better). Capacity for adding new excerpts NOT currently in the PPA will be primarily for rolling copyright items via small-batch each year. 

It would be nice for it to be editable I suppose (in case there's a mistake we need to correct for instance, or we decide we actually want the full work or actually want just an excerpt). But not absolutely essential if we don't have time. It sounds like, though, testing to see whether it works or not at this point would be helpful?

**Comment by rlskoeser** [comment]
> the majority of the article/book excerpt works are works that are currently contained in the PPA in full (maybe 300?). 

I was not aware of this! I knew you had some but I wasn't clear on the scope. This is helpful to know. I'll think about what it means in terms of making the page range editable and adjusting item status for content that's already in the database — it might actually give us a way to test and implement part of the excerpt functionality before building out full import support for excerpts.

**Comment by rlskoeser** [comment]
@mnaydan do you want any validation on the new fields? e.g., should we not allow type = full work if there are pages specified, should we require book/journal title if not a full work? I don't know how much you'll edit this in the admin so I'm not sure how much impact there it to not having it

**Comment by mnaydan** [comment]
@rlskoeser hm. Is the initial import/metadata corrections going to happen en masse via a CSV upload, or will we be fixing the metadata record by record? If we're fixing record by record, it might be important to have the validation scenarios you mention.

**Comment by rlskoeser** [comment]
@mnaydan you have enough of them that we should do the initial import and correction in bulk, but I'm planning to give you a chance to preview/test the excerpt functionality by editing records individually so you can see how it's working so far.

**Comment by mnaydan** [comment]
@rlskoeser gotcha, sounds great! I don't think the validation is essential in that case if it would simplify things for you.

**Comment by rlskoeser** [comment]
@mnaydan thank you for thinking this through with me! Yes, it would be some additional work to implement and test the validation, so I'm happy to skip it. We can always add it later if we discover it is important.

**Comment by mnaydan** [comment]
Tested with chi.19606141 for single range article. Tested with ucm.5326809190 for single range and multirange book excerpt. Tested with hvd.32044098641343 for article with multiple ranges. Everything works as expected, and item type shows on list view & defaults to full.

Invalid page ranges are correctly rejected for non-numeric and for out of sequence. One thing it doesn't catch is page ranges _outside_ of the possible page ranges of the volume. For instance, hvd.32044103001129 has HT pages 1-448. If you put in 500-588, it allows you to save it (but yields no keyword search results, since there's nothing to search! Which makes sense). I don't think this is super important to validate, necessarily, if there's no time -- I trust that most of our data work is accurate, but I thought I'd note it. Would like your opinion on this @rlskoeser but then we can close if you think it's fine.

**Comment by rlskoeser** [comment]
I think it would be hard to validate if the page ranges are outside the actual range, since we only have those numbers once we've calculated the total number of pages (the total isn't provided in the metadata). And only actual pages that exist that are in range would be included in the content that's indexed, so I think it would only result in an inaccurate page count — which doesn't seem terrible to me. (And also probably not very likely to happen)

**Comment by mnaydan** [comment]
Thanks for thinking through it with me! Agreed & makes sense to me.
