### ISSUE TITLE
As a user, when I'm looking at search results I want to see an indicator when something is an excerpt or an article, so that I can tell what kind of content I'm looking at.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#397]
## testing notes
**design links**
[excerpt + article icons](https://zpl.io/VQJdWpA)
- [x] excerpt should have excerpt icon
- [x] article should have article icon
- [x] book/journal title should display in place of full work subtitle

## dev notes
- [x] include item type in work index data
- [x] display excerpt and article icons for items as appropriate
- [x] include book or journal title in search results  _only if_ we can easily integrate it into current format/design

**Comment by mnaydan** [comment]
Placement looks good across browsers and devices. Book/journal title display in subtitle area looks GREAT. Two things:

1) The lines on the book excerpt icon appear distorted, especially on Chrome and FF (screenshot 1) and also when the icon is mobile size (screenshot 2). Perhaps the icon needs to be simplified? 

2) On all browsers if window is sized between full and tablet, icons get cut off (screenshot 3). I think it should either snap to tablet view earlier, or include some left margin padding?

Both of these issues are happening on detail view, too. 

Screenshot 1:
<img width="133" alt="Screen Shot 2021-07-16 at 12 57 13 PM" src="https://user-images.githubusercontent.com/22945600/126341765-b6a43fe4-4d82-4ca1-8be2-2afddf3fad34.png">

Screenshot 2:
<img width="66" alt="Screen Shot 2021-07-20 at 10 11 41 AM" src="https://user-images.githubusercontent.com/22945600/126341773-1b75245a-6ff6-40b5-bee1-304c2143a1f8.png">

Screenshot 3:
<img width="965" alt="Screen Shot 2021-07-20 at 10 12 21 AM" src="https://user-images.githubusercontent.com/22945600/126342045-16286fb9-88f2-4a31-bbb5-5609f8e8a177.png">

**Comment by mnaydan** [comment]
Sorry for the multiple comments. Another couple general things I noticed while testing the other issue:

Sometimes the right line on the article icon disappears. This happens inconsistently to me when browsing. Perhaps due to window size?: 
<img width="945" alt="Screen Shot 2021-07-20 at 10 42 14 AM" src="https://user-images.githubusercontent.com/22945600/126354051-cc302a37-8bff-412a-b85b-44c4cbe50f4f.png">

In the designs the icons are center aligned with each other, on the test site they are right aligned, but the way they are on the test site doesn't really bother me if it's easier to leave. I might actually like it better that way, but thought I'd note, and interested if you have an aesthetic preference...
Design: <img width="536" alt="Screen Shot 2021-07-20 at 11 42 46 AM" src="https://user-images.githubusercontent.com/22945600/126354306-a98c1dfc-a351-44f4-9797-e88d80540268.png">
 
Site: <img width="503" alt="Screen Shot 2021-07-20 at 11 37 28 AM" src="https://user-images.githubusercontent.com/22945600/126354185-9a7c97ab-7d05-44e2-b902-f6135ea45ffa.png">

**Comment by thatbudakguy** [comment]
ok @mnaydan I've made the icons change position earlier so they don't get cut off, and center-aligned the article icon. the other issues i think stem from the icons having very thin lines that browsers don't do a good job rendering, so I'll leave that up to @gissoo to address since it involves editing the actual icon.

**Comment by mnaydan** [comment]
@thatbudakguy thanks, looks great! This is little, but on tablet/mobile the book icon looks misaligned? Like there should be more top padding, no? 
<img width="689" alt="Screen Shot 2021-07-28 at 2 59 35 PM" src="https://user-images.githubusercontent.com/22945600/127380899-9d80946c-2cd8-4695-8904-4ca288c7d723.png">

**Comment by thatbudakguy** [comment]
@mnaydan good catch — adjusted the spacing, lmk if it looks right now

**Comment by mnaydan** [comment]
@thatbudakguy yup, that looks better on desktop and tablet now, thanks. Should I close? What should we do about the icons? I'd rather deploy with them as is if we need to than to have it hold us back. I suppose Meredith can sign off on them next week when I'm away.

**Comment by gissoo** [comment]
@mnaydan thanks for your patience!! I have revised the icon – As Nick said the issue must have been related to how thin the lines were – I looked at the icon on FF and Chrome on desktop and mobile and it looks fine now. I have made the lines thicker now. Please test and see if there are still any issues with it.

**Comment by mnaydan** [comment]
@gissoo thank you!! It does look way better. But I'm noticing that lines are still disappearing ONLY in Chrome. SF and FF look good. 
<img width="291" alt="Screen Shot 2021-07-30 at 4 03 15 PM" src="https://user-images.githubusercontent.com/22945600/127706195-18f50cee-00f8-460b-a8d0-dcfd35174b57.png">
<img width="126" alt="Screen Shot 2021-07-30 at 4 03 00 PM" src="https://user-images.githubusercontent.com/22945600/127706198-96110421-df41-41fe-b163-833e144af9e0.png">

**Comment by gissoo** [comment]
@mnaydan how does it look now? If it looks the same as before then it is a chrome problem!

**Comment by mnaydan** [comment]
@gissoo the top of the book on mobile looks better! The right sides are still missing but let's just shake a fist at Google and close out! Thanks, it looks way better!
