### ISSUE TITLE
Styles: editorial list

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#44]
## dev notes
I've removed the borders between top and bottom of cards, as we discussed at the meeting.

## testing notes
**designs**
[desktop](https://zpl.io/aMdoQXm) / [tablet](https://zpl.io/bAvgD4o) / [mobile](https://zpl.io/aNprDyZ)

**Comment by mnaydan** [comment]
1. The underline bar should be the lighter purple color of the triangle, rather than the more saturated purple.
2. The "Display 6 results" and page numbers aren't present on the test site. But also I DON'T think we'll have enough content that this is necessary to implement by launch.
3. The alignment question that I noted on #62 is relevant here as well. GD's design is more off-kilter (that is, the bar extends further to the right). But if the page numbers aren't present, will extending the bar look weird? I'm torn between making it consistent with the other content pages versus making it look good for this current provisional design.
4. Same cushioning issue between header and landing page title as on #62.

For tablet/mobile:
1. The same grey bar appears on the cards as on #169

**Comment by thatbudakguy** [comment]
updates on this:
1. color has been corrected
2. we came to the same conclusion! adding them depends on #182 , which we decided could wait.
3. my current solution for this (and all content pages) is to keep the margins for all of the content (including pagination) consistent, but extend the header's underline to the right on large screens. you might not see it on your macbook (there's not quite enough space), but slightly larger computers should.
4. I've increased the padding for all content pages.

**Comment by mnaydan** [comment]
1-4 are fixed now, but the card margins are messed up now across devices. Sorry :/ 
<img width="1075" alt="screen shot 2018-12-05 at 3 02 42 pm" src="https://user-images.githubusercontent.com/22945600/49540829-08725800-f89f-11e8-93ad-4a4859a077af.png">

**Comment by mnaydan** [comment]
As mentioned on #173 we'd like to see if updating the headlines to Gentium would work in order to keep it consistent with the headline on the editorial post page. I think eliminating the central bar fixed the space issue, but we'll have to see if that stays true after the font change.

**Comment by thatbudakguy** [comment]
headlines have been updated to Gentium.

**Comment by mnaydan** [comment]
This looks a lot better. I like the consistency and it doesn't mess up the length of the cards/descriptions. Without the center line the descriptions fit now with a headline of max 4 lines and a 1 line author/date.
