### ISSUE TITLE
As a user, I want items with the same title and author to be collapsed automatically so that my search isn’t clouded by repetitive results.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#445]
## testing notes

first round testing (keyword search not yet working; sorting within clusters known to be not working)

- test clusters imported from unique ids CSV file:
   - [x] clusters should be created as needed from the script
   - [x] cluster creation time/source should be documented in a log entry
   - [x] digitized works should be associated with clusters according to the csv
   - [x] digitized works should have a log entry documenting the change
 - clustering search logic
   - [x] in main archive search, only one work from a cluster is shown
   - [x] when clicking through to search within a cluster, all works are shown
   - [x] cluster icon is not displayed when searching within a cluster
   - [x] when searching within a cluster, search terms and filters are applied within that cluster
- test cluster icon display 
   - [x] works that are part of a cluster include the stacked book icon and text with link to search within the cluster
   - [x] document details page for work within a cluster includes stacked book icon and link to search
   - [x] when searching within the cluster, icon and text indicates at top of page
- review cluster icon styles
   - [x] main search results (desktop/tablet/mobile)
   - [x] document detail page (desktop/tablet/mobile)
   - [x] search within a cluster (desktop/tablet/multiple)

see designs for multiple editions in Zeplin: https://app.zeplin.io/project/5be36b3d9dcaf67e95d71839/screen/60c3e0a8929ba112f9f6ee0f

## dev notes
- [x] add group id to digitized work model
- [x] write migration/script to set edition ids from CSV file
- [x] index group id in solr
- [x] group solr results by edition id so that only the first is shown
- [x] display icon for edition/grouped result in search display
- [x] add link to search within result set 
- [x] handle keyword search; display pages + snippets from the correct volume in the cluster
- [x] #512
- [x] #510
- [x] #519

**Comment by mnaydan** [comment]
**Importation functionality:** I randomly spot-checked a handful of records to make sure clusters were created according to the script with associated digitized works (can't think of a more comprehensive way to test). Looks good. Logging is working - on the main log it appears in stages (first logging the addition of a cluster, followed by the changes to works added to that cluster via csv). This makes sense to me. 

**Clustering search logic:** Can't test all of this yet, but what I did test looks good. A question I have is whether on the main search page if you're just "browsing" (no active search), should the clustered items be collapsed? I feel like they should (maybe that's part of the functionality that isn't working yet?)

**Cluster icon display:** Icon placement looks good to me! I am going to show it to MM. I like that it's in the white box at the top, and "Search the full archive" is a much clearer version of what I was going for. 

**Cluster icon styles:** Can't check on my actual phone/tablet because I don't have a PU VPN set up on those devices, but changing my window size on my laptop the styles responded as expected. I'll figure out how to do this by the next round of testing.

**Comment by mnaydan** [comment]
Works within a cluster are being collapsed in browsing mode now, and it looks phenomenal! 

Meredith wondered if there was too much whitespace to the right of the "You are searching and browsing..." message but it doesn't bother me. 

I retested the cluster icon styles on iPhone and iPad and they look good to me; on iPhone the "You are searching and browsing within a cluster" message looks a little cramped because of the way it wraps around the icon but not worth fixing IMO.

Keyword search is the only thing not working now for this issue (and it's actually not working at all - see my comment on #282).

**Comment by mnaydan** [comment]
This looks good! I retested with some searches and (1) clusters are now collapsed on browse and (2) search term persists from main to cluster search. The publications and collections filters plus the sort functionality also appear to be working within cluster search.

The only question I still had (which we happened to be tracking on this issue) is the discrepancies I noticed b/w QA and production: empty result in ballad search and Gale image thumbnails broken.

**Comment by mnaydan** [comment]
I rechecked the new functionality (search persistence and collapse on browse) to make sure the Gale image fix didn't interfere with anything and it looks like everything is working now! RSK told me the empty ballad result was one of the items in QA that doesn't have pairtree data.
