### ISSUE TITLE
upgrade to newer version of nodejs and npm packages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#458]

**Comment by mnaydan** [comment]
- some images are broken in editorial posts and contributor page (I confirmed this behavior is limited to test site, not production)
- Search looks generally ok, but there are a couple funky things:
- I can't reproduce it but one of the searches I made failed to load snippets until refreshing the page. Maybe this was just a fluke. 
- Boolean search is working differently on test versus production. Or maybe it is a snippet problem. From what I can tell, the snippets are cutting off way earlier in test than in production, so that it appears that the test search is only matching one of the two terms for an "AND" search: https://test-ppa.cdh.princeton.edu/archive/?query=%22anapest%22%20AND%20%22Poe%22&collections=9&collections=10&collections=11&collections=3&collections=4&collections=0&sort=relevance versus https://prosody.princeton.edu/archive/?query=%22anapest%22%20AND%20%22Poe%22&collections=9&collections=10&collections=11&collections=3&collections=4&collections=0&sort=relevance

I can keep poking around but that's what I've found so far.

**Comment by rlskoeser** [comment]
I forgot to sync the media files from production to test. (I can't remember now if I updated the database from production! I remember I said I would so we could test what the HathiTrust rsync gives us...)

These sound like they could be indexing problems. Nothing you describe sounds to me like it would be related to the node update

**Comment by rlskoeser** [comment]
Would it be helpful to retest after I refresh data+media from production and reindex everything?

**Comment by mnaydan** [comment]
Oh okay, probably! Should I test the other two features first?

**Comment by rlskoeser** [comment]
@mnaydan yes please — I think you should be able to test them with the site in its current state, and refreshing and reindexing will take a while.

**Comment by mnaydan** [comment]
The pictures are fixed, and we decided to track the snippet issue as a new issue on #463. Neither were related to nodejs, and my testing with the search interface didn't yield anything else unusual, so it seems the nodejs update didn't break anything.
