### ISSUE TITLE
Setup js pipeline with compressor

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#51]
At a minimum I'd like to be able to use ES6 features in the source, so that will require a transpiler in addition to minification.

It might be overkill, but TypeScript could be nice too.

It looks like [this plugin](https://github.com/kottenator/django-compressor-toolkit) actually handles both the scss and ES6 js together, which could be a nice drop-in solution going forward.

**Comment by thatbudakguy** [comment]
this is technically a blocker for #66 since I don't really wanna start writing JS in earnest without a good setup. gonna take a crack at implementing `django-compressor-toolkit` linked above.

**Comment by bwhicks** [comment]
@thatbudakguy Do let me know when you've configured this. There look like a lot of new npm dependencies which will need to be mirrored onto QA and PROD (and tested to make sure they're there correctly).

**Comment by thatbudakguy** [comment]
@bwhicks the way I'm implementing this is just including a `package.json` and lockfile so that you can install all the js dependencies in one step with `npm install`. compressor will look for the dependencies in `node_modules` local to the project folder (or, if it's easier, we could configure it to look anywhere else on the system in prod only). does that sound OK?

**Comment by bwhicks** [comment]
@thatbudakguy This *may* complicate things. I'll need to check the SELinux configs since we've never managed our own `node_modules` before. It seems like the most practical way to handle things though (npm dependencies had been managed globally but this looks like it would work better as part of the build cycle). Go ahead and configure that way, and let me sort out the sanest path for deploys. Thanks!
