### ISSUE TITLE
Can't print more than one page of editorial essay

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#548]
Attempting to print an editorial essay only allows the user to print out whatever fits on one page, and the user is unable to save as PDF or print out the rest of the content. Rebecca believes we had a one-page problem like this before on another site and that it is an overflow setting.

**Comment by mnaydan** [comment]
@rlskoeser this looks great! The entire essays are saveable/printable and span multiple pages: they're readable, sequential, and laying out as expected. And even links are preserved! 

Two small things:
1. There are two extra blank pages at the end of each piece when you save/print it. 
2. Is there a way to scale images? Not an issue for Meredith's pieces, so maybe something we track to implement later. For instance, in Gissoo's essay the floated images are huge and take up the entire page.

**Comment by rlskoeser** [comment]
@mnaydan yes, we can implement different styles for images for print css - let's track that as a new feature and put it off for now.

Not sure about the blank pages! There may be some hidden stuff that is taking up space; I'm inclined to work around that for now, since we can fairly easily remove them for the PDFs we generate in the short term. I'm still investigating better PDF generation that includes header and footer styles like we have for Startwords, but I was having trouble with the tools that do that.

**Comment by mnaydan** [comment]
OK! I think for the purposes then, this is great and we can close & track in new feature.

**Comment by rlskoeser** [comment]
@mnaydan I have a fix for the blank space at the end if you want to confirm

**Comment by mnaydan** [comment]
@rlskoeser ooh, yes! The blank pages are gone! :)
