### ISSUE TITLE
As a user, I want item titles to ignore definite articles and punctuation when sorting, so that I can find the most relevant content first.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#56]
## notes for testing
When you sort on title in the public search powered by Solr, it should now sort on the same sort titles that you can view and edit in the admin interface (see #100 )

## dev notes
- need to update form to sort items on the new sort title field

**Comment by rlskoeser** [comment]
@mnaydan oh! interesting (and what careful testing!). My guess is that it has something to do with upper / lower case (I think the database is sorting case-insensitive, so `c` comes before `e`, but Solr is sorting case-sensitive, so upper case comes before lower case). You can edit the chanson record sort title to make the C upper case and see how it behaves in both sorts (you can edit other records too, if it helps you understand what's going on).

So, this raises a question: should the public title sort be case-sensitive or not?

**Comment by mnaydan** [comment]
@rlskoeser oh that's smart, I didn't think of that, and that is exactly what's going on. And it's actually messing up a lot of records on the public site--it's correctly ignoring the definite and indefinite articles, but all of the uppercase keywords are frontloaded (A-Z on pages 1-64) and the lowercase are backloaded (a-z (but little) again on pages 65-101). I think the public site should be case insensitive like the database, because I don't think capitalization in the 19th c was really standardized, nor I'm guessing is Hathi. What do you think?

There's also a few weird cases where titles are in brackets (like mdp.39015024941604) because Hathi provided a missing title, causing them to come between the A-Z sort and the a-z sort on the public site and causing them to come at the very end of the admin site ([Pamphlet...] is sorting on the [ instead of the P) . Should we write a script to get rid of that punctuation in the sort title, like we did for the blank spaces? Or is it fine for them to sort on the [ ]?

**Comment by rlskoeser** [comment]
@mnaydan I agree, case-insensitive sort makes sense for this content. We've done that before for other projects, I can look at implementing that here. If basic sort is working, would it make sense to you if we make a new ticket for that so we can close this one and include the current implementation in a release? 

Also: are you aware of any accented characters or unicode that need to be handled in the sort or search? Because we can include that in the index updates if we need to.  See e.g. the Derrida's Margins project, where you can search with and without accents for content.

I think removing the brackets is reasonable for our purposes; I don't think we care that it was supplied or inferred.  I have an issue about getting cleaner metadata from the Hathi import -  #118  - what do you think about starting to keep a list of things we know we want to clean? I would also like to remove the trailing slash from titles; pretty sure it's a cataloging thing we don't care about. I think trailing punctuation on publisher and place of publication could go, and would love to remove the 'printed for' kind of text we have in a lot of places, if we can come up with enough of a list of them.

**Comment by mnaydan** [comment]
@rlskoeser I'll close this ticket out and make a new one for case-insensitive sort. (Removing the brackets will be part of the metadata cleaning I'm guessing?)

Off the top of my head, I can't answer the accented/unicode character question right now. I'm less familiar with the contents of the archive than Meagan was, and I'd have to look at a CSV. But everything in the archive is supposed to be English-language only, right, so I wouldn't think so? I can check and get back to you.

I agree about keeping a metadata cleaning list--does it make sense to keep track of it on issue #118? I also wanted to ask you about the title slash and figured it was imported from the Hathi MARC stuff.

**Comment by rlskoeser** [comment]
@mnaydan let's repurpose #118 and start our list there; suggestions for how to relabel? I still have some more investigation I'd like to do, and wanted to consult with some metadata experts about some questions, but I'm not sure what should be done when.
