### ISSUE TITLE
work on a script to automate reporting on and potentially fixing updated digital page ranges for excerpted works

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#560]
Spreadsheet: [https://docs.google.com/spreadsheets/d/19OOnnWL2_fERrXw1Znw6JWNyh-X3b2ir/edit?usp=sharing&ouid=114207920712086651571&rtpof=true&sd=true](https://docs.google.com/spreadsheets/d/19OOnnWL2_fERrXw1Znw6JWNyh-X3b2ir/edit?usp=sharing&ouid=114207920712086651571&rtpof=true&sd=true)

Plan is to filter the spreadsheet to the corrections and see how close the current script gets us so that we can figure out which changes need to be made.

**Comment by mnaydan** [comment]
At our meeting on 2/28/24 we discussed building the automated checking functionality and using this spreadsheet as a way to verify the results of the new script rather than running the spreadsheet through to make a quick fix.

**Comment by rlskoeser** [comment]
@mnaydan I did some preliminary investigation on the simpler approach we discussed in our meeting, using page labels from the METS structmap, and it looks promising. Can you help me come up with the list of fields you'd want to see in a report for comparing automated checks with the correction spreadsheet?  (Maybe we could decide at iteration planning?)

**Comment by mnaydan** [comment]
@rlskoeser and I discussed this at iteration planning and we decided we would need the following fields:
- Source ID
- Source ID + digital page range (unique ID for url slugs)
- Original page range
- Old digital page range
- Corrected digital page range

**Comment by mnaydan** [comment]
During iteration planning today we decided that we should send this report to Brian at the same time that it's delivered to me for testing as well.

**Comment by rlskoeser** [comment]
Ran the rsync in staging to make sure we were checking against most recent hathitrust data, then ran the new script to check the excerpt page ranges against labels in the METS structmap.

Here's the CSV generated by that script:
[ppa-excerpt-pagecheck.csv](https://github.com/Princeton-CDH/ppa-django/files/14641518/ppa-excerpt-pagecheck.csv)

I'm curious how this correlates with the dates for changes that @laurejt  found and the hand-curated corrected page ranges in the other spreadsheet.

@mnaydan I added hathitrust links to the report because I thought it might help expedite spot-checking the results. I don't know if we'll want to keep this report long-term, but if we do maybe last-modified dates would be helpful.

**Comment by mnaydan** [comment]
@rlskoeser I started a [spreadsheet spot-checking the results](https://docs.google.com/spreadsheets/d/1lZNxI3PYUbwhZqLhByYed54ULPTQ_IGweeIbNGVPBek/edit?usp=sharing).

I spot-checked 11 records, and _all_ of the entries in pages_digital_corrected are incorrect (I'm guessing this is the field that automated the page range fixes based on the METS mapping?). Meaning, it's 1) logging changed ranges when the ranges did _not_ change 2) logging no changes when page range _did_ change, and 3) making incorrect changes when page range did change. All of these errors are off by 2 or 4 pages.

**Comment by rlskoeser** [comment]
@mnaydan I think this must mean that my logic is wrong rather than that the page labels in the METS are unreliable, because it looks like the page labels appear correctly in the HT interface, and I presume they are coming from the METS.

I'll take another crack at this using your spot-checked examples and see if I can figure out where my logic is off.

I wondered why so many were showing up as changed, when I knew that you had reported not so many changed overall!

**Comment by mnaydan** [comment]
@rlskoeser I put the CSV into a [Google Sheet](https://docs.google.com/spreadsheets/d/1f-1sDYVbsWH_Yd07lU7o_4NgOmCqHPY1-gLVWN7-aFA/edit?usp=sharing) and color-coded/hand-checked them all. There's a color key at the bottom of the sheet. Overall, the script did pretty well! Some patterns in the errors:

- Some proposed range changes are just wrong and I'm not sure why
- Some are wrong due to HT page anomalies
- Some, oddly, produce numbers outside of the possible digital range
- The script is consistently wrong for excerpts from MLN, which has 3 page numbers per page (upper left, upper right, center bottom)
- Script reports on no page label in METS and unable to parse due to roman numerals
- The syntax output is really weird for uc1.c2641998. It looks like this: -582--581,-548
- I wasn't able to test whether the script missed content that DID change. It did occasionally propose changes when the original digital range was correct.

What this all tells me is that it doesn't make sense to automatically change ranges; there's too much weirdness. Also, as I cross-checked this spreadsheet against the one my undergrad made, about 20 of those ranges had changed AGAIN since she completed the spreadsheet in August/September 2023, so building into our rsync workflow alerts to possible changes to investigate makes sense to me. Do you think it makes sense to fix them from the spreadsheet once, and then run a cron job to identify likely range changes (N in the match column) to alert admin to investigate? I'm wondering how this intersects with @laurejt's version label investigation - eyeballing it it looks like all the ones in the undergrad spreadsheet that were wrong were updated sometime between September 2023 and now.

**Comment by rlskoeser** [comment]
@mnaydan thank you for your careful and thorough testing! I'm inclined to agree with you - I could improve the logic some, but it doesn't seem like there's enough justification to do that since it isn't reliable enough across all cases.

I like your proposal: I'll see if I can update the excerpt script to update page ranges, so we can apply the current known corrections; and then the rsync workflow should have a step specific to excerpts : check and flag for review if the page labels don't match or can't be checked.

I think we should close this issue - we've done the reporting and determined that automatically fixing the ranges isn't reliable. Let's create a new one for the excerpting batch-fix (unless you can find an existing issue; I think I may have rewritten this one when we decided to try a different approach), and then we'll need a new one for the ongoing check as part of the rsync workflow.
