### ISSUE TITLE
As a user, I want to search and browse digitized volumes by keyword so that I can see what materials are in the archive.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#6]
## Notes for testing
* Simple keyword search on anything in basic metadata and full text
* Basic display (no styles, limited formatting) provided for testing search functionality.  Does not yet have a custom default sort or handle pagination.
* Searches across book metadata and page contents, grouping all pages and book together; book should always be retrieved for display even if the only matches are in pages of the book.
* Currently supports keyword, exact phrase (use quotes) and also boolean searching - default behavior is *OR*, but you can specify *AND*.  I'm not sure if we want to preserve this behavior or not, but probably worth testing to get an idea how it works.
* Updates 12/14:
  * results are sorted by title by default; sorted by relevance when a search term is entered
  * now has basic pagination displayed at the bottom of the page; for now, showing 50 items per page
  * now displaying the first handful of pages for each volume
  * when there is a keyword search, I'm also displaying relevance per page
  * I'm currently displaying relevance for the group, but it's always 1.0, so there's something off there but I'm not sure what yet
   * I looked up the **near** search syntax, if you want to try that: `"grammar children"~4`, where 4 is the maximum number of words apart
   * please also test searches with bad syntax to see how it's handled; I've tried e.g. `"incomplete quote` or incomplete boolean such as `thing OR`; you may be able to think of others.

---
- [x] default sort
- [x] pagination
- [x] display list of matching page numbers for testing
- [x] unit tests

**Comment by mm4CDH** [comment]
Only displaying first 50 results. Helpful to know! 
Tested "dictionary" and "pronouncing" (over 4500) to try to test metadata -- titles seemed to work. 
Tested Iamb, iambic, iambus & got back different results so also seemed to work.

**Comment by mm4CDH** [comment]
Searched Longfellow, he came up. Will try a few more authors.

**Comment by meagan1019** [comment]
I tested:
- terms with an asterisk (worked)
- phrase in quotation (worked)
- terms with a tilde (not sure)
- author and title metadata (worked)
- boolean and/or (seemed to work)

I would like to see the pages the keyword is on so I can confirm (by looking at source @ Hathi) that search returns the instance on the page rather than in the metadata (which is being displayed)

**Comment by mm4CDH** [comment]
Searched two authors Brewer Saintsbury, returned both (Or) but then tried AND but nothing changed. Then searched "Brewer" and "Saintsbury" and results decreased to 5.

**Comment by mm4CDH** [comment]
NEVERMIND maybe it was an uppercase lowercase issue.

**Comment by mm4CDH** [comment]
Tired to test words within a page Saintsbury AND ballad AND bone

**Comment by mm4CDH** [comment]
SolR searches seem to also function so BONUS.

**Comment by mm4CDH** [comment]
I searched for a simple keyword (amphibrach" and it worked. 
I cannot click on the page in Hathi to see where the word is on the Hathi page but I don't think that is what we're testing right now. 

Following Meagan's tests from before and am also checking page numbers. 

terms with an asterisk -- this was hard to test since our search isn't yet giving us the page images for each page, so it took awhile to click on all of the Hathi pages, plus (as I wrote in the other review page) we need Hathi to ALWAYS open in a new window if possible. 

Searched for iamb* and tested _Foreign Sources of Modern Versification_ tried to find iamb / iambic / any variation on page 98 and didn't see it. Also didn't see it on page 10. There is no page 113 so I think I must be reading the page numbers incorrectly and am therefore testing incorrectly? It's clearly in the title but I can't find it elsewhere. 

phrase in quotation here I tested "iambic" and oddly _Foreign Sources of Modern Versification_ came up again but that's probably because it's in the title. Went to American Phonetic Dictionary p. 240 but that's definitely the wrong page (M page). I think the pagination might be off -- tried "Childhood" and looked at page 35 also no dice.
terms with a tilde (not sure)
author and title metadata seemed to work. Tried Emerson, Saintsbury, Blair. Title worked. 
boolean and/or (seemed to work)

Couldn't get to Boolean unfortunately! Arg!

**Comment by mm4CDH** [comment]
Ok tried to do Boolean and it seemed to work fine -- AND gives far fewer results than OR. 
I'm going to write "needs attention" so maybe RK or BH can tell me how to read the page numbers and then I can test full-text for real. 

Everything seems great except that I don't know how to read the page numbers, or maybe they are displaying incorrectly.

**Comment by rlskoeser** [comment]
@mm4CDH thank you for all the testing and helpful feedback!

I meant to investigate how pages are displayed in Hathi to check that the labels I'm displaying were useful before I delivered this for testing, but I forgot.

@meagan1019 or @mm4CDH can you provide more details about what information you need to be able to match pages?  Are you looking for the page label that's displayed in the "jump to" section of the HT book viewer?  

<img width="176" alt="screen shot 2018-01-04 at 10 15 47 am" src="https://user-images.githubusercontent.com/691231/34569992-7b171536-f138-11e7-9148-db2032234c52.png">

I see that the METS files included in the data have an `ORDER` and an `ORDERLABEL` attribute for each page, but it also looks like not every volume has order labels.  Here's an example of one of those: https://babel.hathitrust.org/cgi/pt?id=aeu.ark:/13960/t1pg22p71;view=1up;seq=28 
That one has empty order labels for everything but the last page; other volumes have empty order labels for some pages (e.g. cover and title pages) but order labels for other pages.  Any thoughts on how you want to handle this?

I notice some other information about the pages in the METS; they look sort of like tags (image on page, blank, untypical page), and I wonder if these would be useful.  If I need to use the METS to get page labels, we might think about indexing these labels as well.  Here's an example:  
```
<METS:div ORDER="1" LABEL="FRONT_COVER, IMAGE_ON_PAGE, IMPLICIT_PAGE_NUMBER" TYPE="page">
        <METS:fptr FILEID="HTML00000001"/>
        <METS:fptr FILEID="TXT00000001"/>
        <METS:fptr FILEID="IMG00000001"/>
      </METS:div>
      <METS:div ORDER="2" LABEL="IMAGE_ON_PAGE, UNTYPICAL_PAGE, IMPLICIT_PAGE_NUMBER" TYPE="page">
        <METS:fptr FILEID="HTML00000002"/>
        <METS:fptr FILEID="TXT00000002"/>
        <METS:fptr FILEID="IMG00000002"/>
      </METS:div>
      <METS:div ORDER="3" LABEL="BLANK, IMPLICIT_PAGE_NUMBER" TYPE="page">
        <METS:fptr FILEID="HTML00000003"/>
        <METS:fptr FILEID="TXT00000003"/>
        <METS:fptr FILEID="IMG00000003"/>
      </METS:div>
      <METS:div ORDER="4" LABEL="BLANK, IMPLICIT_PAGE_NUMBER" TYPE="page">
        <METS:fptr FILEID="HTML00000004"/>
        <METS:fptr FILEID="TXT00000004"/>
        <METS:fptr FILEID="IMG00000004"/>
      </METS:div>
```

**Comment by meagan1019** [comment]
@rlskoeser @mm4CDH For the page being displayed, it is not the "jump to" box, but the last number in the html link. For example, if I search "kangaroo," the first work I get is The American phonetic dictionary of the English language. The page is listed as 0000270. When I go to the work in HT (https://babel.hathitrust.org/cgi/pt?id=nyp.33433075923916;view=1up;seq=1) I change the last "1" in the HTML to "270" and, voilà there is "kangaroo":

https://babel.hathitrust.org/cgi/pt?id=nyp.33433075923916;view=1up;seq=270
![screen shot 2018-01-04 at 5 32 44 pm](https://user-images.githubusercontent.com/4306343/34587286-bb3d2636-f175-11e7-9f79-288d65428749.png)

**Comment by meagan1019** [comment]
Oh HT you are so annoying with your metadata! Does the above help with these empty order labels? Scrolling through every page is numbered via the "HTML00000001"... For those without correct pagination (which I am guessing is using the tag "ORDER"?), we could generate from that.

**Comment by rlskoeser** [comment]
@meagan1019 thanks, this is helpful.  What I'm displaying right now is actually the image filename without the extension - I think this is _often_ the same as the sequence number but I'm not sure that it's guaranteed to be.  Can you do a little more testing on what's currently on the test site to see if what we have now is sufficient?  If I recall, our purpose for displaying pages was so you could confirm the search is behaving properly in terms of which pages it's finding - could you look at a few more volumes and see if you're comfortable signing off that it's behaving properly?

We can always revisit the page details later (in terms of order, order label, and the other tags) when we have a specific need or use for it.

**Comment by meagan1019** [comment]
This was actually fun! So many of my results came back with scansion and other funky marks, but still were returned in search! So exciting! I know that I searched "midnight dreary" on our previous solr instance and did not get many of these results returned. Amazing!

I re-tested: 
- terms with an asterisk: amphibra* --> checked top five entries by relevance at Hathi, some with multiple entries (worked)
- phrase in quotation: "midnight dreary" --> checked top five entries by relevance at Hathi (worked)
- terms with a tilde: romantic~ --> returned terms like "romantick" and "romanticism" (worked)
- author and title metadata: guest rhythms --> top 3 returns were _A history of English rhythms_ by Edwin Guest (worked)
- boolean or: kangaroo OR crocodile --> way more references to crocodile lol (worked)
- boolean and: kangaroo AND crocodile --> (worked)

Meredith might also want to test to see how robust/how well search follows her research needs. Also because it's fun and amazing to see how well it works! I'm still going to mark as complete to not hold up development. 

Meredith, the way to test is:
1) do your search term (asterisk, tilde, etc.)
2) right click the Hathi volumes ID link to open your search result in a new tab (i.e. nyp.33433082512108)
3) in the Hathi window URL, scroll to the very end and insert the page number that returned (i.e. search result says "1 page; pages 00000114" change "https://babel.hathitrust.org/cgi/pt?id=nyp.33433082512108;view=1up;seq=9" to "https://babel.hathitrust.org/cgi/pt?id=nyp.33433082512108;view=1up;seq=114"
4) look for your search term on that page

**Comment by rlskoeser** [comment]
Thanks @meagan1019 !  So glad to hear this is working so well!  Thanks for documenting so clearly what you tested and how to compare in Hathi, that is super helpful.
