### ISSUE TITLE
write code so that all note types in eebo-xml appear at bottom of page instead of inline

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#665]

**Comment by rlskoeser** [comment]
@jerielizabeth I was able to get all the EEBO-TCP pages indexed with the new logic, but I had to do it a few ids at a time. When I try to index all of them, either by id or by source, the indexing hangs at some point. This didn't happen when I indexed locally (although I thought I saw one error which I then couldn't duplicate); I'll see if I can isolate whether a particular volume is causing the problem. Maybe Laure will spot the problem in her code review.

This issue has some comments from when Mary and I were investigating the EEBO-TCP xml:
https://github.com/Princeton-CDH/ppa-django/issues/659

It includes some examples of texts with notes of various kinds with links so you can see how they display on the U Michigan site and the text content around and in the note.

Here are a couple of searches on the test site for content near footnotes where you can now see a footnote indicator rather than the inline footnote contents (as was happening previously):
https://test-prosody.cdh.princeton.edu/archive/A66045/?query=%22handling+of+that+subject%22
https://test-prosody.cdh.princeton.edu/archive/CW0116702026/?query=%22Exact+propriety+of+word+and+thought+%22

**Comment by jerielizabeth** [comment]
I tested the functionality using a jsonl file provided by @rlskoeser for item [A68619](http://name.umdl.umich.edu/A68619.0001.001) in EEBO (PPA link: https://test-prosody.cdh.princeton.edu/archive/A68619/) 

Examples of working as expected include the following pages:

- p. 137: [PPA](https://test-prosody.cdh.princeton.edu/archive/A68619/?query=%22by+vs+the+Ringleader%22) | [UMich](https://quod.lib.umich.edu/e/eebo2/A68619.0001.001?rgn=main;view=fulltext#fnDLPS3) | 4 expected citations in the text, text for which does appear at the bottom of the "text" field in the jsonl file.
- p 158: [PPA](https://test-prosody.cdh.princeton.edu/archive/A68619/?query=%22Or+when+we+speake+by+manner+of+pleasantery%22) | [UMich](https://quod.lib.umich.edu/e/eebo2/A68619.0001.001?rgn=main;view=fulltext#fnDLPS40) | example of footnote content being outside the displayed text as expected.
- p. 200: [PPA](https://test-prosody.cdh.princeton.edu/archive/A68619/?query=%22Pragmatographia.+or+the+Counterfait+action%22) | [UMich](https://quod.lib.umich.edu/e/eebo2/A68619.0001.001?rgn=main;view=fulltext#fnDLPS105) | example of footnote content only being pulled, with text from an earlier footnote as well. 

I tested the following citation flags: *, †,§. There were no pages with enough citations to reach ** or beyond. 
This appears to me to be working as expected, keeping the footnote text with the page, and with a character and leading \n structure that should make it possible to isolate.
