### ISSUE TITLE
As a user, I want to search digitized volumes by keyword author names in a clearly marked author search field so that I can see what materials are in the archive by a certain author.

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-django#67]

**Comment by rlskoeser** [comment]
@mnaydan revised your wording slightly to "filter digitized volumes by keywords in author name" to clarify my understanding/expectation of what we're trying to do.  Please let me know if that's inaccurate or I'm missing something!  (Same for #68 )

**Comment by rlskoeser** [comment]
@mnaydan augh, "filter" is a loaded term isn't it?  I'm not referring to the author filter that Xinyi designed (we're not planning to build that right now).  I say keyword because I would expect you to use this in roughly the same way you do the main text search - e.g. you can search for just "Walker" and not have to know the exact way the name is in the database.  You'll be able to use the same wildcards and phrases you can use there also.

I revised to filter because "browse by author" suggests more of a sorting function than.  Is "limit" any better?

**Comment by rlskoeser** [comment]
@meagan1019 I like that wording - also makes the distinct input field explicit

**Comment by meagan1019** [comment]
This works amazing! Searched keyword "raven AND poe" with book title "rhythm" and it worked flawlessly. Tried keyword "raven OR poe" with title "poetry." My only question is why "Collections" is showing up as tiles to the left (see screenshot). I even deleted one such collection from the admin site ("37 test") and it's still there.

**Comment by meagan1019** [comment]
<img width="1019" alt="screen shot 2018-05-17 at 3 33 08 pm" src="https://user-images.githubusercontent.com/4306343/40199786-89ce24ca-59e8-11e8-8916-10d89a3e318d.png">

**Comment by rlskoeser** [comment]
@meagan1019 deleting collections from the admin and having that synced to the Solr index is a known issue (not yet supported).  I'm sure that "37 Test" was a test collection someone added to the test site for testing purposes, since we don't have more collections created yet.

Your notes sound like you tested title (#68) rather than author (although they are closely related and should work very similarly).

The collection buttons you're seeing are based on Xinyi's design - you should be able to click on a collection to limit your results to only those items in that collection (can also do multiple collections).

**Comment by meagan1019** [comment]
@rlskoeser yes I added it. Sorry I did test title. Retested with keyword "roar" and author "smith." Returned 35 works. None of the collections buttons are working. When I click any (or multiple), the works displayed remain at 35.
