### ISSUE TITLE
As a user, I want to see basic details for individual items in the archive so that I can see the record details and get to the HathiTrust version.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#7]
## Notes for testing
- accessible from search results or from admin interface (use the 'view on site' button)
- display is provisional and unstyled

**Comment by mm4CDH** [comment]
It's great to see the record number so I can click to the Hathi version. Now that I am looking at it, I realize that this link could be a button that says "view item in Hathi" instead of that long record details, since that's really more for us. I think it's messy to have it on the front-end. But the link needs to be live to the site, so that is what I'll test. 

Clicking on the live record number link, I notice that it needs to open in a new window automatically. 

Searching inside an item for a word doesn't yet take us to the page where that word appears in Hathi; that isn't what we're testing. Because that isn't working yet. 

Since the Hathi URL contains the record id inside it, I'm not sure that we need to list both on the single item page, maybe just keep this record for us as admins and have some button that says "access Hathi" and then after a search (from the search results page with the pages from Hathi) "access page in Hathi" or something like that?
