### ISSUE TITLE
Histogram dates are unordered

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#78]
my local (correct): 
<img width="446" alt="screen shot 2018-05-18 at 11 35 05 am" src="https://user-images.githubusercontent.com/4924494/40243947-8e743a3a-5a8f-11e8-9432-14a5beff64e6.png">
qa current:
<img width="693" alt="screen shot 2018-05-18 at 11 35 40 am" src="https://user-images.githubusercontent.com/4924494/40243966-9e3cab1e-5a8f-11e8-98f4-c7295abc0996.png">

the `<dt>` and `<dd>` elements are appearing out of order (not arranged chronologically) which leads me to believe that results in `facet_ranges.pub_date` in the view context are unordered in qa for some reason.

**Comment by rlskoeser** [comment]
This is happening because SolrClient returns facets and facet ranges as `dict` rather than `OrderedDict` - made a fork with the fix and have a pull request to contribute it back.  (Probably not obvious because order is not _guaranteed_ but can be preserved).   

I now see that the SolrClient codebase hasn't been that active in a while and the build is broken; hopefully we'll still get a response and can get it folded in and released.    We can install from my forked version of SolrClient for now.

**Comment by mnaydan** [comment]
This seems to be working properly. I tried an author search with "Bysshe" that returned 12 results and the bar distribution seems to correspond to the years. I also tried keyword searches and most of them look like Nick's local example above. The data would be more meaningful, I think, if you could hover over a bar and see the year, but that's an extra want rather than a functional issue, so I'll close.
