### ISSUE TITLE
sort options should be drop down with native selector on mobile

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/ppa-django#84]
Perhaps we can re-render the same Django form field with a select widget? Render both and show the appropriate one.

**Comment by thatbudakguy** [comment]
rather than stacking the menu items, I'm showing the dropdown on any screens smaller than M (1068px), because it looks less awkward imo.

just noticed that semantic UI doesn't support using the native UI for its dropdowns, which is annoying. that said, it works fairly OK on mobile. what are people's thoughts on how it looks now?

**Comment by thatbudakguy** [comment]
Closing since current implementation works.
