### ISSUE TITLE
Histogram min/max dates aren't displaying

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#95]
## testing notes
- The min/max dates for the histogram visualization should display underneath it, at either end
- the dates should update when you change the date range or new results are loaded
- the dates should match the ones that you specify in the date range box

**Comment by mnaydan** [comment]
On desktop, histogram min/max dates display correctly and update correctly when new dates are input (sometimes it takes 4-5 seconds to update). If an invalid date is entered it will display the invalid date, unless "0" is entered in which case they default to 1559 and 1922. The question of displaying invalid dates shouldn't be an issue if we resolve #105.  

Other things appear to be broken with the histogram, however, as I noted on Slack. If the year span is small enough(?) when doing a keyword search the histogram only shows bars for the start and end date, and it's blank in between. That doesn't seem right? Here are two screenshots of the search "iamb" with different year spans.
<img width="735" alt="screen shot 2018-10-25 at 3 08 10 pm" src="https://user-images.githubusercontent.com/22945600/47525465-52612a80-d86b-11e8-8f3a-a76f0d754395.png">
<img width="720" alt="screen shot 2018-10-25 at 3 11 57 pm" src="https://user-images.githubusercontent.com/22945600/47525469-542aee00-d86b-11e8-9fe0-35487dbfbe6b.png">


On iPad, the issue is that the min/max date will change before the results are actually submitted and the histogram results are loaded. If we are using the return button to submit the form on iPad, I think it makes sense for the dates not to change until the form is submitted. Otherwise it looks confusing, like maybe it was submitted but the histogram isn't showing up. See screenshots:
![img_0004b58c7738-1](https://user-images.githubusercontent.com/22945600/47525217-addee880-d86a-11e8-94d7-541aebb26e90.jpeg)
![img_1fce8c16c65b-1](https://user-images.githubusercontent.com/22945600/47525223-b1726f80-d86a-11e8-952a-205f4ca8b9cf.jpeg)

On mobile, the min/max range changes according to the values input but the histogram results don't load when you press "done" (see screenshot). If you press return the page reloads and it takes you back to the simple search and page of results (i.e., you can't see the histogram search you just entered). So maybe for mobile the histogram results need to load automatically after inputting them (or after pressing "done")? But also I don't think it's a priority to see the histogram on mobile...
![img_4d1b73e348ac-1](https://user-images.githubusercontent.com/22945600/47525325-f696a180-d86a-11e8-9187-199664ace907.jpeg)

**Comment by thatbudakguy** [comment]
@mnaydan I tested on desktop and changing the min/max years is correctly reloading the form for me. Try switching between the default range vs. 1900-1922 - that change is drastic enough that you can see it in the results (but other date ranges might not change the results much).

in terms of pressing enter/hitting Done - this should never do anything. the form should always update when you put things in the date range boxes, no matter what screen size/device type. I think the mobile device might display the "Done" button because it "knows" that it's in a form; I'll probably need to find a way to disable that so that people don't accidentally reload the page using it.

I think part of the confusion is that something is definitely wrong with the drawing of the bars right now...some date ranges that _should_ have bars in them are drawing incorrectly so that it appears that the histogram is empty, or mostly empty. I think that might be what you're seeing on iPad too. I'll look into it...thanks for being thorough!

**Comment by thatbudakguy** [comment]
@rlskoeser I think something's up with solr. I tested with the date range 1860-1887 and got this data:
```
        {"gap": 1, "end": 1887, "counts": {"1860": 48, "1861": 0, "1862": 0, "1863": 0, "1864": 0, "1865": 0, "1866": 0, "1867": 0, "1868": 0, "1869": 0, "1870": 0, "1871": 0, "1872": 0, "1873": 0, "1874": 0, "1875": 0, "1876": 0, "1877": 0, "1878": 0, "1879": 0, "1880": 0, "1881": 0, "1882": 0, "1883": 0, "1884": 0, "1885": 0, "1886": 45}, "start": 1860}
```
(basically, ~45 results on each end and nothing in the middle). this happens for lots of date ranges near to this range, but I can see in the result list tons of results from 1869, 1865...all sorts of stuff that should be in the middle.

**Comment by mnaydan** [comment]
@thatbudakguy is something wrong with the "displaying number of results" then? The number of results for me doesn't change after inputting the min/max years, even after waiting upwards of 10 seconds. It doesn't change until I press enter. You can see the disparity of results in the two screenshots I took below--the first after changing the min/max years and waiting, the second after pressing enter. This is aside from the histogram display/solr issue you've noted. Does the number of results change for you automatically? 
<img width="736" alt="screen shot 2018-10-30 at 12 28 46 pm" src="https://user-images.githubusercontent.com/22945600/47733991-d89cb880-dc3f-11e8-8763-d32fc9171739.png">
<img width="763" alt="screen shot 2018-10-30 at 12 29 04 pm" src="https://user-images.githubusercontent.com/22945600/47733994-daff1280-dc3f-11e8-9a4d-fe938a3c7400.png">

**Comment by mnaydan** [comment]
@thatbudakguy this seems to be working fine now across devices. The results counts are updating, pressing enter does nothing, and the min/max dates display/change when you change them.

The histogram is still broken, but I think this is covered in #124. There's also the question of displaying invalid dates (right now it displays an invalid 4 digit date (e.g., 1440), and displays the first 2-3 digits of a 5+ digit number (e.g., 18 for 18889). But that should be covered in #105. So I'll close out of this one?
